In [2]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os
import re
load_dotenv()

True

In [4]:
url="https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM"
payload = dict(KEY=os.getenv("gg_api"), Type="json", pIndex=1, pSize=10)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.json()
response

https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM?KEY=78c71dfbaa4e4a6da7ff4083edb8d6ac&Type=json&pIndex=1&pSize=10
200

{'TBGGDLNGPRCAPTTRDSRCM': [{'head': [{'list_total_count': 134842},
    {'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다.'}},
    {'api_version': '1.0'}]},
  {'row': [{'NO': 134904,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '996',
     'LOTNO_ORIGNO': '996',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '주공그린빌',
     'PRVTUSE_AR': 84.8,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '1~10',
     'DELNG_AMT': 26900,
     'FLOOR_NM': '5',
     'BUILD_YY': '2003',
     'ROAD_NM': '통일로802번길',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 관산동'},
    {'NO': 134905,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '996',
     'LOTNO_ORIGNO': '996',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '주공그린빌',
     'PRVTUSE_AR': 75.95,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '11~20',
     'DELNG_AMT': 27000,
     'FLOOR_NM': '10',
     'BUILD_YY': '2003',
     'ROAD_NM': '통일로802번길',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 관산동'},
    {'NO': 134906,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '996',
     'LOTNO_ORIGNO': '996',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '주공그린빌',
     'PRVTUSE_AR': 84.51,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '11~20',
     'DELNG_AMT': 25500,
     'FLOOR_NM': '2',
     'BUILD_YY': '2003',
     'ROAD_NM': '통일로802번길',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 관산동'},
    {'NO': 134907,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '996',
     'LOTNO_ORIGNO': '996',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '주공그린빌',
     'PRVTUSE_AR': 59.92,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '11~20',
     'DELNG_AMT': 23700,
     'FLOOR_NM': '10',
     'BUILD_YY': '2003',
     'ROAD_NM': '통일로802번길',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 관산동'},
    {'NO': 134908,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '996',
     'LOTNO_ORIGNO': '996',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '주공그린빌',
     'PRVTUSE_AR': 84.8,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '11~20',
     'DELNG_AMT': 27450,
     'FLOOR_NM': '4',
     'BUILD_YY': '2003',
     'ROAD_NM': '통일로802번길',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 관산동'},
    {'NO': 134909,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '983',
     'LOTNO_ORIGNO': '983',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '엘에이치원흥도래울마을2단지',
     'PRVTUSE_AR': 74.98,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '11~20',
     'DELNG_AMT': 37800,
     'FLOOR_NM': '19',
     'BUILD_YY': '2014',
     'ROAD_NM': '도래울로',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 도내동'},
    {'NO': 134910,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '983',
     'LOTNO_ORIGNO': '983',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '엘에이치원흥도래울마을2단지',
     'PRVTUSE_AR': 84.98,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '11~20',
     'DELNG_AMT': 40000,
     'FLOOR_NM': '24',
     'BUILD_YY': '2014',
     'ROAD_NM': '도래울로',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 도내동'},
    {'NO': 134911,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '983',
     'LOTNO_ORIGNO': '983',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '엘에이치원흥도래울마을2단지',
     'PRVTUSE_AR': 74.98,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '11~20',
     'DELNG_AMT': 36800,
     'FLOOR_NM': '13',
     'BUILD_YY': '2014',
     'ROAD_NM': '도래울로',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 도내동'},
    {'NO': 134912,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '983',
     'LOTNO_ORIGNO': '983',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '엘에이치원흥도래울마을2단지',
     'PRVTUSE_AR': 84.98,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '11~20',
     'DELNG_AMT': 39500,
     'FLOOR_NM': '21',
     'BUILD_YY': '2014',
     'ROAD_NM': '도래울로',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 도내동'},
    {'NO': 134913,
     'REFINE_STATE_CD': None,
     'LOTNO_ADDR': '1011',
     'LOTNO_ORIGNO': '1011',
     'LOTNO_VICENO': '0',
     'HSCOMPLEX_NM': '엘에이치원흥도래울마을4단지',
     'PRVTUSE_AR': 59.92,
     'CONTRACT_YM': '2018-01',
     'CONTRACT_DAY': '1~10',
     'DELNG_AMT': 34900,
     'FLOOR_NM': '14',
     'BUILD_YY': '2013',
     'ROAD_NM': '도래울3로',
     'REFINE_CMPLT_YN': None,
     'CREAT_DE': None,
     'REFINE_LOTNO_ADDR': None,
     'REFINE_ROADNM_ADDR': None,
     'REFINE_ZIPNO': None,
     'REFINE_WGS84_LOGT': None,
     'REFINE_WGS84_LAT': None,
     'REFINE_MANAGE_NO': None,
     'REFINE_RESLT_CD': None,
     'REFINE_ADDR_DIV_CD': None,
     'REFINE_SYS_DIV_CD': None,
     'REFINE_DTM': None,
     'REFINE_NOADMIT_YN': None,
     'ADDR': '경기도 고양덕양구 도내동'}]}]}

In [11]:
total_pages = response["TBGGDLNGPRCAPTTRDSRCM"][0]['head'][0]['list_total_count'] // 1000 + 1
total_pages

135

In [22]:
cols = ['NO', 'LOTNO_ADDR', 'LOTNO_ORIGNO', 'LOTNO_VICENO',
       'HSCOMPLEX_NM', 'PRVTUSE_AR', 'CONTRACT_YM', 'CONTRACT_DAY',
       'DELNG_AMT', 'FLOOR_NM', 'BUILD_YY', 'ROAD_NM', 'ADDR']

In [23]:
result = {}
for item in response["TBGGDLNGPRCAPTTRDSRCM"][1]['row']:
    for key, value in item.items():
        if key in cols:
            result.setdefault(key, []).append(value)
        
df = pd.DataFrame(result)
df

,NO,LOTNO_ADDR,LOTNO_ORIGNO,LOTNO_VICENO,HSCOMPLEX_NM,PRVTUSE_AR,CONTRACT_YM,CONTRACT_DAY,DELNG_AMT,FLOOR_NM,BUILD_YY,ROAD_NM,ADDR
0,134904,996,996,0,주공그린빌,84.80,2018-01,1~10,26900,5,2003,통일로802번길,경기도 고양덕양구 관산동
1,134905,996,996,0,주공그린빌,75.95,2018-01,11~20,27000,10,2003,통일로802번길,경기도 고양덕양구 관산동
2,134906,996,996,0,주공그린빌,84.51,2018-01,11~20,25500,2,2003,통일로802번길,경기도 고양덕양구 관산동
3,134907,996,996,0,주공그린빌,59.92,2018-01,11~20,23700,10,2003,통일로802번길,경기도 고양덕양구 관산동
4,134908,996,996,0,주공그린빌,84.80,2018-01,11~20,27450,4,2003,통일로802번길,경기도 고양덕양구 관산동
5,134909,983,983,0,엘에이치원흥도래울마을2단지,74.98,2018-01,11~20,37800,19,2014,도래울로,경기도 고양덕양구 도내동
6,134910,983,983,0,엘에이치원흥도래울마을2단지,84.98,2018-01,11~20,40000,24,2014,도래울로,경기도 고양덕양구 도내동
7,134911,983,983,0,엘에이치원흥도래울마을2단지,74.98,2018-01,11~20,36800,13,2014,도래울로,경기도 고양덕양구 도내동
8,134912,983,983,0,엘에이치원흥도래울마을2단지,84.98,2018-01,11~20,39500,21,2014,도래울로,경기도 고양덕양구 도내동
9,134913,1011,1011,0,엘에이치원흥도래울마을4단지,59.92,2018-01,1~10,34900,14,2013,도래울3로,경기도 고양덕양구 도내동

In [21]:
df.columns

Index(['NO', 'REFINE_STATE_CD', 'LOTNO_ADDR', 'LOTNO_ORIGNO', 'LOTNO_VICENO',
       'HSCOMPLEX_NM', 'PRVTUSE_AR', 'CONTRACT_YM', 'CONTRACT_DAY',
       'DELNG_AMT', 'FLOOR_NM', 'BUILD_YY', 'ROAD_NM', 'REFINE_CMPLT_YN',
       'CREAT_DE', 'REFINE_LOTNO_ADDR', 'REFINE_ROADNM_ADDR', 'REFINE_ZIPNO',
       'REFINE_WGS84_LOGT', 'REFINE_WGS84_LAT', 'REFINE_MANAGE_NO',
       'REFINE_RESLT_CD', 'REFINE_ADDR_DIV_CD', 'REFINE_SYS_DIV_CD',
       'REFINE_DTM', 'REFINE_NOADMIT_YN', 'ADDR'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NO                  10 non-null     int64
 1   REFINE_STATE_CD     0 non-null      object
 2   LOTNO_ADDR          10 non-null     object
 3   LOTNO_ORIGNO        10 non-null     object
 4   LOTNO_VICENO        10 non-null     object
 5   HSCOMPLEX_NM        10 non-null     object
 6   PRVTUSE_AR          10 non-null     float64
 7   CONTRACT_YM         10 non-null     object
 8   CONTRACT_DAY        10 non-null     object
 9   DELNG_AMT           10 non-null     int64
 10  FLOOR_NM            10 non-null     object
 11  BUILD_YY            10 non-null     object
 12  ROAD_NM             10 non-null     object
 13  REFINE_CMPLT_YN     0 non-null      object
 14  CREAT_DE            0 non-null      object
 15  REFINE_LOTNO_ADDR   0 non-null      object
 16  REFINE_ROADNM_ADDR  0 non-null      object
 17  REFINE_ZIPNO        0 non-null      object
 18  REFINE_WGS84_LOGT   0 non-null      object
 19  REFINE_WGS84_LAT    0 non-null      object
 20  REFINE_MANAGE_NO    0 non-null      object
 21  REFINE_RESLT_CD     0 non-null      object
 22  REFINE_ADDR_DIV_CD  0 non-null      object
 23  REFINE_SYS_DIV_CD   0 non-null      object
 24  REFINE_DTM          0 non-null      object
 25  REFINE_NOADMIT_YN   0 non-null      object
 26  ADDR                10 non-null     object
dtypes: float64(1), int64(2), object(24)
memory usage: 2.2+ KB

In [19]:
pd.DataFrame(response["TBGGDLNGPRCAPTTRDSRCM"][1]['row'])

,NO,REFINE_STATE_CD,LOTNO_ADDR,LOTNO_ORIGNO,LOTNO_VICENO,HSCOMPLEX_NM,PRVTUSE_AR,CONTRACT_YM,CONTRACT_DAY,DELNG_AMT,...,REFINE_ZIPNO,REFINE_WGS84_LOGT,REFINE_WGS84_LAT,REFINE_MANAGE_NO,REFINE_RESLT_CD,REFINE_ADDR_DIV_CD,REFINE_SYS_DIV_CD,REFINE_DTM,REFINE_NOADMIT_YN,ADDR
0,134904,None,996,996,0,주공그린빌,84.80,2018-01,1~10,26900,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
1,134905,None,996,996,0,주공그린빌,75.95,2018-01,11~20,27000,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
2,134906,None,996,996,0,주공그린빌,84.51,2018-01,11~20,25500,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
3,134907,None,996,996,0,주공그린빌,59.92,2018-01,11~20,23700,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
4,134908,None,996,996,0,주공그린빌,84.80,2018-01,11~20,27450,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 관산동
5,134909,None,983,983,0,엘에이치원흥도래울마을2단지,74.98,2018-01,11~20,37800,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 도내동
6,134910,None,983,983,0,엘에이치원흥도래울마을2단지,84.98,2018-01,11~20,40000,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 도내동
7,134911,None,983,983,0,엘에이치원흥도래울마을2단지,74.98,2018-01,11~20,36800,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 도내동
8,134912,None,983,983,0,엘에이치원흥도래울마을2단지,84.98,2018-01,11~20,39500,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 도내동
9,134913,None,1011,1011,0,엘에이치원흥도래울마을4단지,59.92,2018-01,1~10,34900,...,None,None,None,None,None,None,None,None,None,경기도 고양덕양구 도내동

# 전체 페이지 수집하기

In [1]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os
import re
load_dotenv()
import time

In [2]:
page_num = 1
total_pages = 1
result = {}

while page_num <= total_pages:
    url="https://openapi.gg.go.kr/TBGGDLNGPRCAPTTRDSRCM"
    payload = dict(KEY=os.getenv("gg_api"), Type="json", pIndex=page_num, pSize=1000)
    r = requests.get(url, params=payload)
#     print(r.url)
#     print(r.status_code)
    response = r.json()

    if total_pages == 1:
        total_pages = response["TBGGDLNGPRCAPTTRDSRCM"][0]['head'][0]['list_total_count'] // 1000 + 1
    else:
        pass

    print(f"{page_num}/{total_pages}데이터 수집중", end="\r")
    
    cols = ['NO', 'LOTNO_ADDR', 'LOTNO_ORIGNO', 'LOTNO_VICENO',
           'HSCOMPLEX_NM', 'PRVTUSE_AR', 'CONTRACT_YM', 'CONTRACT_DAY',
           'DELNG_AMT', 'FLOOR_NM', 'BUILD_YY', 'ROAD_NM', 'ADDR']

    
    for item in response["TBGGDLNGPRCAPTTRDSRCM"][1]['row']:
        for key, value in item.items():
            if key in cols:
                result.setdefault(key, []).append(value)
                
    page_num += 1  
    time.sleep(0.2)
                
        
df = pd.DataFrame(result)
df

,NO,LOTNO_ADDR,LOTNO_ORIGNO,LOTNO_VICENO,HSCOMPLEX_NM,PRVTUSE_AR,CONTRACT_YM,CONTRACT_DAY,DELNG_AMT,FLOOR_NM,BUILD_YY,ROAD_NM,ADDR
0,134904,996,996,0,주공그린빌,84.80,2018-01,1~10,26900,5,2003,통일로802번길,경기도 고양덕양구 관산동
1,134905,996,996,0,주공그린빌,75.95,2018-01,11~20,27000,10,2003,통일로802번길,경기도 고양덕양구 관산동
2,134906,996,996,0,주공그린빌,84.51,2018-01,11~20,25500,2,2003,통일로802번길,경기도 고양덕양구 관산동
3,134907,996,996,0,주공그린빌,59.92,2018-01,11~20,23700,10,2003,통일로802번길,경기도 고양덕양구 관산동
4,134908,996,996,0,주공그린빌,84.80,2018-01,11~20,27450,4,2003,통일로802번길,경기도 고양덕양구 관산동
...,...,...,...,...,...,...,...,...,...,...,...,...,...
134837,269497,Jun-49,49,6,남수원현대,84.98,2018-10,11~20,14500,4,1997,화산로,경기도 화성시 안녕동
134838,269498,Jun-49,49,6,남수원현대,59.98,2018-10,21~31,14600,5,1997,화산로,경기도 화성시 안녕동
134839,269499,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,1~10,19000,15,2006,효행로,경기도 화성시 안녕동
134840,269500,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,1~10,17800,1,2006,효행로,경기도 화성시 안녕동
134841,269501,211,211,0,다솜마을동문굿모닝힐,84.99,2018-10,11~20,21900,15,2006,효행로,경기도 화성시 안녕동