# YES24에서 베스트셀러 정보 수집하기

In [1]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [23]:
url = "https://www.yes24.com/product/category/bestseller"
payload = dict(categoryNumber="001", pageNumber=1, pageSize=120)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = bs(r.content, 'lxml')
response

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200

<!DOCTYPE html>
<html lang="ko">
<head><link href="https://m.yes24.com/Home/Best?DispNo=001" media="only screen and(max-width: 640px)" rel="alternate"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
<meta content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" http-equiv="Accept-CH"/>
<meta content="86400" http-equiv="Accept-CH-Lifetime"/>
<meta content="unsafe-url" name="referrer"/>
<meta content="width=1170" name="viewport"/>
<title> 국내도서 종합 베스트 - 예스24 </title>
<meta content="예스24" name="title"/>
<meta content="YOUR EVERY STORY 문화 콘텐츠 플랫폼, 예스24" name="description"/>
<meta content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" name="keywords"/>
<link href="//www.yes24.com/OpensearchDescription.xml" rel="search" title="YES24" type="application/opensearchdescription+xml"/>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/util.js?v=20250709" type="text/javascript"></script>
<script charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20250618" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20250618" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/Javascript/Search/bulletSearch.js?v=20250702" type="text/javascript"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20250910" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20250730" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20250730" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/frontCommon.js?v=20250903" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20250730" type="text/javascript"></script>
<link charset="euc-kr" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20250916" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20250818" rel="stylesheet" type="text/css"/>
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
	<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		// dfinery 디파이너리 위한 설정 값
		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
<script src="https://www.yes24.com/javascript/common.js?v=20250903" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250916" type="text/javascript"></script>
<script src="https://image.yes24.com/static/logging/clickstream.min.js?v=20250709" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/dfinery.min.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/dfineryHelper.js?v=20250613" type="text/javascript"></script>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager -->
<script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
<!-- End Google Tag Manager -->
<!-- RTB HOUSE 메인 태깅 코드 -->
<script>
	    (function(w,d,dn,t){w[dn]=w[dn]||[];w[dn].push({eventType:'init',value:t,dc:'asia'});
	    var f=d.getElementsByTagName('script')[0],c=d.createElement('script');c.async=true;
	    c.src='https://tags.creativecdn.com/ld87UMn0bZ6wjXtzlyVc.js';
	    f.parentNode.insertBefore(c,f);})(window,document,'rtbhEvents','ld87UMn0bZ6wjXtzlyVc');
	    (rtbhEvents = window.rtbhEvents || []).push({});
    </script>
<!-- End RTB HOUSE 메인 태깅 코드 -->
<link href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20251013" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?ver=20250818" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/best/best.css?ver=20250818" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/yesLocation.css?ver=20250818" media="all" rel="stylesheet" type="text/css"/></head>
<body>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
<dt>콘텐츠 바로가기</dt>
<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>
<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div class="" id="yesWrap">
<div id="yesHeaderArea" style="">
<!-- ########## TOPBANNER 영역 시작 ########## -->
<section>
<div id="upperBnWrap" style="display:none;">
<div id="upperBnRoll">
<div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#d2eeff"><a href="https://event.yes24.com/onlyApp" onclick="setWcode('001');"><img alt="도서앱" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1015_topbn_480x50_L_01.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#bbd5ff"><a href="https://event.yes24.com/present?eventNo=263495" onclick="setWcode('001');"><img alt="북파우치카드케이스" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1015_topbn_480x50_R_01.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#fcffc8"><a href="https://event.yes24.com/yesBenefit" onclick="setWcode('001');"><img alt="10월혜택" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1015_topbn_480x50_L_02.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#d3c3ff"><a href="https://event.yes24.com/present?eventNo=263495" onclick="setWcode('001');"><img alt="북파우치카드케이스" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1015_topbn_480x50_R_02.png" width="480"/></a></div>
</div>
</div>
</div>
<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
</div>
</section>
<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
<!-- ########## TOPBANNER 영역 끝 ########## -->
<!-- ########## HEADER 영역 시작 ########## -->
<div id="yHeader">
<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onclick="setWcode('001_004');"><svg aria-label="YES24" role="img" type="image/svg+xml"><image alt="YES24" height="103" src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" width="200" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" xmlns:xlink="http://www.w3.org/1999/xlink"/></svg></a></h1>
<div id="yHeaderWrap">
<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
<div class="yHeaderTop">
<h2 class="yBlind">YES24 카테고리 리스트</h2>
<ul class="cateLi" id="ulCategoryList"><li class="cate001 cateOn"><a href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" title="국내도서"><em class="txt">국내도서</em></a></li><li class="cate002"><a href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002" onclick="setWcode('001_002_002')" title="외국도서"><em class="txt">외국도서</em></a></li><li class="cate018"><a href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" title="중고샵"><em class="txt">중고샵</em></a></li><li class="cate017"><a href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')" title="eBook"><em class="txt">eBook</em></a></li><li class="cateCrC"><a href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')" title="크레마클럽"><em class="txt">크레마클럽</em><em class="ico_newSup"></em></a></li><li class="cate003"><a href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" title="CD/LP"><em class="txt">CD/LP</em></a></li><li class="cate004"><a href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" title="DVD/Blu-ray"><em class="txt">DVD/BD</em></a></li><li class="cate006"><a href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" title="GIFT"><em class="txt"><u>문구</u>/GIFT</em></a><span class="gSticker"><a href="https://event.yes24.com/diaryShop">2026 다이어리</a></span></li><li class="cateENT"><a href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank" title="티켓"><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
<h2 class="yBlind">YES24 유틸메뉴</h2>
<ul class="utilLi">
<li id="LoginText">
<input id="hdfLoginYn" type="hidden" value="N"/>
<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>
</li>
<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>
<li class="myPgGrp">
<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
<dl class="myPgDl">
<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
<dd>
<ul>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
</ul>
</dd>
</dl>
</li>
<li><a href="https://ssl.yes24.com/Cart/Cart" onclick="setWcode('001_003_010')"><em class="txt">카트</em></a></li>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_011')"><em class="txt">주문/배송</em></a></li>
<li class="lastLi"><a href="https://www.yes24.com/Templates/FTCusMain.aspx?Wcode=001_003_012" onclick="setWcode('001_003_012')"><em class="txt">고객센터</em></a></li>
</ul>
<dl class="globalYesInfoDl">
<dt><a href="javascript:void(0);"><em class="txt">Global YES24</em><em class="ico_arr bgGNB">안내보기</em></a></dt>
<dd>
<div class="globalYesInfoContArea">
<div class="globalYesInfoCont">
<p class="yesInfo_tit">Global YES24는?</p>
<p class="yesInfo_des">
									K-POP/K-Drama 관련상품(음반,도서,DVD)을<br/> 영문/중문 으로 이용하실 수 있습니다.
								</p>
<div class="yesInfo_globalTxt">
<p class="globalTxt_des">
										Korean wave shopping mall, sell the <br/>K-POP/K-Drama (CD,DVD,Blu-ray,Book)
										We aceept PayPal/UnionPay/Alipay<br/> and support English/Chinese Language service
									</p>
<a class="btnC btn_blue" href="https://global.yes24.com" onclick="setWcode('001_016_002')" target="_blank"><span class="bWrap"><em class="txt">English</em></span></a>
<p class="globalTxt_des">
									 作为出售正规 K-POP/K-Drama 相关(CD,图书,DVD) 韩流商品的网站, 支持 中文/英文 等海外结账方式
									</p>
<a class="btnC btn_blue" href="https://cn.yes24.com" onclick="setWcode('001_016_003')" target="_blank"><span class="bWrap"><em class="txt">中文</em></span></a>
<p class="globalTxt_des">
									 Exclusive ticket sales for domestic and international pop artists
									</p>
<a class="btnC btn_blue" href="http://ticket.yes24.com/English?Gcode=009_205" onclick="setWcode('001_016_004')" target="_blank"><span class="bWrap"><em class="txt">Global yesticket</em></span></a>
</div>
</div>
</div>
</dd>
</dl>
</div>
<!-- %%%%%%%%%% 해더 Top 영역 끝 %%%%%%%%%% -->
<hr/>
<!-- %%%%%%%%%% 해더 Mid 영역 시작 %%%%%%%%%% -->
<div class="yHeaderMid">
<div class="yesSearch">
<form accept-charset="utf-8" action="//www.yes24.com/product/search?" id="yesSForm" method="get" name="HeadForm" onsubmit="return check_search();">
<input id="keywordAd" name="keywordAd" type="hidden" value=""/>
<input id="keyword" name="keyword" type="hidden"/>
<input id="domain" name="domain" type="hidden" value="ALL"/>
<input id="qdomain" name="qdomain" type="hidden" value="전체"/>
<fieldset>
<legend>검색</legend>
<span class="schIpt">
<label><input accesskey="s" autocomplete="off" class="iptTxt" id="query" maxlength="80" name="query" onblur="blurSearchBar();" onfocus="showLatestSearchList();" onkeydown="SearchBarRenderingEnableSet(false);init_searchbox();" onmousedown="SearchBarRenderingEnableSet(false);Common_init_searchbox();" style="ime-mode: active;" title="YES24 검색어 입력" type="text" value=""/></label>
</span>
<div style="position:absolute;top:-1000em;left:0;width:1px;height:1px;overflow:hidden;">
<script charset="euc-kr" src="//adgirl.yes24.com/RealMedia/ads/adstream_mjx.ads/www.yes24.com/Header/SearchBar@x01" type="text/javascript"></script>
<script type="text/javascript">
							try {
								OAS_RICH("x01");
							} catch (e) { }
						</script>
</div>
<script type="text/javascript">
						var url = location.href;
						var reUrl = url.toLowerCase();

						$(document).ready(function () {
							//검색결과
						    if (reUrl.indexOf('/product/search') > -1 && reUrl.indexOf('/product/search/searchkeyword') <= 0) {
								SearchBarRenderingEnable = false;

								if (getParamValue("query") != undefined) {
									$("#query").val($("#hidSearchWord").val());
									fnGetValueDomain($("#hidSearchDomain").val());
									$("#domain").val($("#hidSearchDomain").val());
									$("#qdomain").val($("#hidSearchQdomain").val());
								}
							}
							if (SearchBarRenderingEnable == true) {
								fnSearchBarRendering();
							}
						});

						// 검색어 입력창에 포커스 시
						function SearchBarRenderingEnableSet(enable) {
							//광고 제거
							SearchBarRenderingEnable = enable;
							$("#ulSchScopeOpt").hide();
						}

						// 검색어 입력창 광고 노출
						function fnSearchBarRendering() {
							var seardtext = $('#hdSearchBarText').val();
							var bannerLink = $("#hdSearchBarLink").val();

							$('#query').val(seardtext);
							$('#query').addClass("iptTxt iptTxtAd");
							$('#keywordAd').val(bannerLink);
						}

						//검색창 선택 시
						function showLatestSearchList() {
							SearchBarRenderingEnableSet(false);
							if (String($("input#query").val()).length == 0) {
								try{
									srchHistory.show();
								}catch(e){}
								$("#suggestSearchList").hide();
								$("#searchKeyLayer").show();
								$("#latestSearchList").show();
							} else {
								BulletSearchRenewal.InitBulletSearch();
								showSuggestSearchList();
							}
						}

						//검색창 포커스 아웃
						function blurSearchBar() {
							var queryValue = $("#query").val();
							if (queryValue == "" || queryValue == null) {
                                if (location.href.toLowerCase().indexOf('/product/search') == -1) {
                                    fnSearchBarRendering();
                                    query_init = false;
								}
							}
						}

						function hideLatestSearchList() {
							$("#searchKeyLayer").hide();
							$("#latestSearchList").hide();
						}

						//추천검색어
						function showSuggestSearchList() {
							var domainVal = String($("#qdomain").val());

In [35]:
book_list = response.select("#yesBestList > li")
book_list

[<li class="" data-goods-no="153064968" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">1</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/153064968" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="트렌드 코리아 2026" border="0" class="lazy" data-original="https://image.yes24.com/goods/153064968/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(153064968); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 <span class="gd_keynote" id="spanGdKeynote">
 <a class="iconC tBook" href="/24/Category/More/001014?ElemNo=13&amp;ElemSeq=1&amp;Gcode=000_030_001"><em class="txt">오늘의책</em></a>
 <!-- 클래스24 상품일 경우 -->
 </span>
 <script type="text/javascript">
         if ($('#spanGdKeynote').children().length == 0) {
             $('#spanGdKeynote').remove();
         }
     </script>
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/153064968" onclick="wiseLogV2('BS', '001_005_001', ''); ">트렌드 코리아 2026</a>
 <span class="gd_nameE">2026 대한민국 소비트렌드 전망</span>
 <a class="bgYUI ico_nWin" href="/product/goods/153064968" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">트렌드 코리아 2026 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EB%2582%259C%25EB%258F%2584&amp;authorNo=133431&amp;author=김난도" target="">김난도</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2584%25EB%25AF%25B8%25EC%2598%2581&amp;authorNo=140108&amp;author=전미영" target="">전미영</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25EC%25A7%2580%25ED%2598%259C&amp;authorNo=157166&amp;author=최지혜" target="">최지혜</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B6%258C%25EC%25A0%2595%25EC%259C%25A4&amp;authorNo=236190&amp;author=권정윤" target="">권정윤</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25EB%258B%25A4%25ED%2598%259C&amp;authorNo=295621&amp;author=한다혜" target="">한다혜</a> 저 외 7명
                                         <span class="moreAuthArea">
 <span class="moreAuthBtn"><a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.cCont_listArea'),event);">정보 더 보기/감추기</a></span>
 <span class="moreAuthLi">
 <span class="moreAuthLiCont">
 <ul>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EB%2582%259C%25EB%258F%2584&amp;authorNo=133431&amp;author=김난도" target="">김난도</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2584%25EB%25AF%25B8%25EC%2598%2581&amp;authorNo=140108&amp;author=전미영" target="">전미영</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25EC%25A7%2580%25ED%2598%259C&amp;authorNo=157166&amp;author=최지혜" target="">최지혜</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B6%258C%25EC%25A0%2595%25EC%259C%25A4&amp;authorNo=236190&amp;author=권정윤" target="">권정윤</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25EB%258B%25A4%25ED%2598%259C&amp;authorNo=295621&amp;author=한다혜" target="">한다혜</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25ED%2598%259C%25EC%259B%2590&amp;authorNo=361117&amp;author=이혜원" target="">이혜원</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%2588%2598%25EC%25A7%2584&amp;authorNo=190906&amp;author=이수진" target="">이수진</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%259C%25EC%259C%25A0%25ED%2598%2584&amp;authorNo=190905&amp;author=서유현" target="">서유현</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2584%25EB%258B%25A4%25ED%2598%2584&amp;authorNo=409052&amp;author=전다현" target="">전다현</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%25A4%2580%25EC%2598%2581&amp;authorNo=140104&amp;author=이준영" target="">이준영</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25ED%2596%25A5%25EC%259D%2580&amp;authorNo=140106&amp;author=이향은" target="">이향은</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EB%2582%2598%25EC%259D%2580&amp;authorNo=483435&amp;author=김나은" target="">김나은</a></li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%af%b8%eb%9e%98%ec%9d%98%ec%b0%bd&amp;query=%25EB%25AF%25B8%25EB%259E%2598%25EC%259D%2598%25EC%25B0%25BD">미래의창</a></span>
 <span class="authPub info_date">2025년 09월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=261904">[단독] 스틸 펜트레이 (포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">18,000</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">20,000</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>1,000원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 397,884
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/153064968?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">66</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_10">리뷰 총점</span><em class="yes_b">9.5</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (34건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (4건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (26건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (2건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EB%258B%25AC%25EC%259D%2598%25EA%25B5%25BF%25EC%25A6%2588&amp;hashNm=%ec%9d%b4%eb%8b%ac%ec%9d%98%ea%b5%bf%ec%a6%88" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '이달의굿즈', '153064968','6788');">#이달의굿즈</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%258A%25B8%25EB%25A0%258C%25EB%2593%259C%25ED%2582%25A4%25EC%259B%258C%25EB%2593%259C&amp;hashNm=%ed%8a%b8%eb%a0%8c%eb%93%9c%ed%82%a4%ec%9b%8c%eb%93%9c" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '트렌드키워드', '153064968','782');">#트렌드키워드</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2586%258C%25EB%25B9%2584%25ED%258A%25B8%25EB%25A0%258C%25EB%2593%259C&amp;hashNm=%ec%86%8c%eb%b9%84%ed%8a%b8%eb%a0%8c%eb%93%9c" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '소비트렌드', '153064968','645');">#소비트렌드</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=2026%25EB%25A5%25BC%25EC%2598%2588%25EC%25B8%25A1%25ED%2595%2598%25EB%258B%25A4&amp;hashNm=2026%eb%a5%bc%ec%98%88%ec%b8%a1%ed%95%98%eb%8b%a4" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '2026를예측하다', '153064968','8951');">#2026를예측하다</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">사은품</em></span>
 <span class="txt"><a href="https://event.yes24.com/earlyReader?eventNo=263557">이달의 책 10월 : 화조도 카드 케이스</a></span>
 <span class="date">(25.10.01 ~ 25.10.31)</span>
 </div>
 </div>
 <div class="info_row info_relG">
                     관련상품 :                            <span class="relG"><a href="/product/goods/155311099">eBook <span class="relG_num">14,000원</span></a></span>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="153064968" id="ordChk_153064968" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_153064968" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('153064968'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('153064968'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('153064968', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('153064968', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" name="btnList" onclick="order_payment.addMyListV3('153064968', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_153064968" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":153064968,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"02","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"트렌드 코리아 2026","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001013","goodsSortNm":"경제 경영","goodsAuth":"&lt;김난도&gt;,&lt;전미영&gt;,&lt;최지혜&gt;,&lt;권정윤&gt;,&lt;한다혜&gt;,&lt;이혜원&gt;,&lt;이수진&gt;,&lt;서유현&gt;,&lt;전다현&gt;,&lt;이준영&gt;,&lt;이향은&gt;,&lt;김나은&gt; 저","shopPrice":20000.00,"salePrice":18000.00,"discountShopPrice":2000.00}'/>
 </div>
 </div>
 </li>,
 <li class="" data-goods-no="60543924" data-iy-no="0" data-statgb="01">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">2</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/60543924" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="사탄탱고" border="0" class="lazy" data-original="https://image.yes24.com/goods/60543924/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(60543924); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 <span class="gd_keynote" id="spanGdKeynote">
 <span class="iconC reserv"><em class="txt">예약판매</em></span>
 <a class="lnk_series" href="javascript:void(0);" onclick="openUrl('/product/category/series/001?SeriesNumber=267333','Pcode','003_001')">알마 인코그니타</a>
 ,                <a class="lnk_series" href="javascript:void(0);" onclick="openUrl('/product/category/series/001?SeriesNumber=364766','Pcode','003_001')">2025 노벨문학상 수상작가</a>
 <!-- 클래스24 상품일 경우 -->
 </span>
 <script type="text/javascript">
         if ($('#spanGdKeynote').children().length == 0) {
             $('#spanGdKeynote').remove();
         }
     </script>
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/60543924" onclick="wiseLogV2('BS', '001_005_001', ''); ">사탄탱고</a>
 <span class="gd_feature">
                         [
 <span class="feature">2025 노벨문학상 수상 작가</span>                        ]
                     </span>
 <a class="bgYUI ico_nWin" href="/product/goods/60543924" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">사탄탱고 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2581%25AC%25EB%259F%25AC%25EC%258A%25A4%25EB%2584%2588%25ED%2598%25B8%25EB%25A5%25B4%25EC%25BB%25A4%25EC%259D%25B4%2520%25EB%259D%25BC%25EC%258A%25AC%25EB%25A1%259C&amp;authorNo=216254&amp;author=크러스너호르커이 라슬로" target="">크러스너호르커이 라슬로</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A1%25B0%25EC%259B%2590%25EA%25B7%259C&amp;authorNo=134143&amp;author=조원규" target="">조원규</a> 역
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%95%8c%eb%a7%88&amp;query=%25EC%2595%258C%25EB%25A7%2588">알마</a></span>
 <span class="authPub info_date">2018년 05월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=263532">패브릭 독서대/자수 레터링 책갈피 선택가능(포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">17,820</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">19,800</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>990원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 119,997
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/60543924?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">27</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_10">리뷰 총점</span><em class="yes_b">9.1</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (11건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (12건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (4건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_signature">
                     2025 노벨문학상 수상 작가
                 </div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%2585%25B8%25EB%25B2%25A8%25EB%25AC%25B8%25ED%2595%2599%25EC%2583%2581%25EC%2588%2598%25EC%2583%2581%25EC%259E%2591%25EA%25B0%2580&amp;hashNm=%eb%85%b8%eb%b2%a8%eb%ac%b8%ed%95%99%ec%83%81%ec%88%98%ec%83%81%ec%9e%91%ea%b0%80" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '노벨문학상수상작가', '60543924','1585');">#노벨문학상수상작가</a>
 </span>
 </div>
 <div class="info_row info_relG">
                     관련상품 :                            <span class="relG"><a href="/product/goods/116613404">eBook <span class="relG_num">13,800원</span></a></span>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="60543924" id="ordChk_60543924" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_60543924" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('60543924'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('60543924'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('60543924', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('60543924', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" name="btnList" onclick="order_payment.addMyListV3('60543924', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_60543924" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":60543924,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"01","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"사탄탱고","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001033","goodsSortNm":"소설/시/희곡","goodsAuth":"&lt;크러스너호르커이 라슬로&gt; 저/&lt;조원규&gt; 역","shopPrice":19800.00,"salePrice":17820.00,"discountShopPrice":1980.00}'/>
 </div>
 </div>
 </li>,
 <li class="" data-goods-no="153497469" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">3</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/153497469" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="절창 切創" border="0" class="lazy" data-original="https://image.yes24.com/goods/153497469/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>

In [36]:
len(book_list)

120

# li 1개는 1권의 정보
* 책 제목, 저자, 출판사, 출간일, 가격, 평점, 리뷰수

In [18]:
def text_clean(text):
    text = text.replace("\n", "").replace("\r", "").replace(",", "").replace("저", "").replace("역", "").strip()
    return text

In [6]:
# 책 제목
book_title = book_list[0].select_one(".gd_name").text

In [13]:
book_list[0].select_one(".authPub.info_auth").text

'\n김난도, 전미영, 최지혜, 권정윤, 한다혜 저 외 7명\r\n                                        \n정보 더 보기/감추기\n\n\n\n김난도\n전미영\n최지혜\n권정윤\n한다혜\n이혜원\n이수진\n서유현\n전다현\n이준영\n이향은\n김나은\n\n\n\n\n'

In [89]:
df

,저,원저,글,역,글그림,사진,감수,그림,공저,기획,출판사,출간일,가격,평점,리뷰수
0,김난도 전미영 최지혜 권정윤 한다혜 이혜원 이수진 서유현 전다현 이준영 이향은 김나은,,,,,,,,,,미래의창,2025년 09월,18000,9.5,66
1,크러스너호르커이 라슬로,,,조원규,,,,,,,알마,2018년 05월,17820,9.1,27
2,구병모,,,,,,,,,,문학동네,2025년 09월,16200,9.4,109
3,프리드리히 니체,,,,,,,,,,떠오름,2025년 03월,16020,9.5,422
4,김도윤 정태익 김광석 김승주 김용섭 김학렬 김현준 최재붕,,,,,,,,,,북모먼트,2025년 09월,23400,9.5,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,한국데이터진흥원,,,,,,,,,,한국데이터산업진흥원,2023년 12월,17460,9.3,116
116,헤르만 헤세,,,전영애,,,,,,,민음사,2000년 12월,7200,9.3,1097
117,신영준 고영성 편,,,,,,,,,,상상스퀘어,2025년 10월,22500,8.0,4
118,최태성,,,,,,,,,,이투스북,2024년 12월,17550,9.9,174
119,후지모토 타츠키 글그림,,,,,,,,,,학산문화사,2021년 09월,5400,9.9,267

김난도
전미영
최지혜
권정윤
한다혜
이혜원
이수진
서유현
전다현
이준영
이향은
김나은

In [19]:
text_clean(book_list[7].select_one(".authPub.info_auth").text)

'오태민 손혜민 김유정'

In [29]:
# 저자와 역자가 같이 있을 때 저자
text_clean(book_list[1].select_one(".authPub.info_auth").text.split("/")[0])

'크러스너호르커이 라슬로'

In [30]:
# 저자와 역자가 같이 있을 때 역자
text_clean(book_list[1].select_one(".authPub.info_auth").text.split("/")[1])

'조원규'

In [39]:
# 저자가 1명일 때
author = text_clean(book_list[2].select_one(".authPub.info_auth").text)

In [43]:
# 출판사
publisher = book_list[0].select_one(".authPub.info_pub > a").text

In [66]:
# 출간일
pub_date = book_list[0].select_one(".authPub.info_date").text

In [51]:
# 책 가격
price = int(book_list[0].select_one(".yes_b").text.replace(",", ""))

In [56]:
# 평점
rating = float(book_list[0].select_one(".rating_grade > .yes_b").text)

In [64]:
# 리뷰수
n_reviews = int(book_list[0].select_one(".rating_rvCount > a > em.txC_blue").text)

In [67]:
print(book_title, author, publisher, pub_date,  price, rating, n_reviews)

트렌드 코리아 2026 구병모 미래의창 2025년 09월 18000 9.5 65

# 페이지 전체에 있는 책 정보 하나로 모으기

In [76]:
result = {}
keys = ['제목', '저자', '출판사', '출간일', '가격', '평점', '리뷰수']
for idx ,book in enumerate(book_list):
    print(f"{idx+1}/{len(book_list)}")
    book_title = book.select_one(".gd_name").text
    author = text_clean(book.select_one(".authPub.info_auth").text)
    publisher = book.select_one(".authPub.info_pub > a").text
    pub_date = book.select_one(".authPub.info_date").text
    price = int(book.select_one(".yes_b").text.replace(",", ""))
    rating = float(book.select_one(".rating_grade > .yes_b").text) if book.select_one(".rating_grade > .yes_b") != None else 0
    n_reviews = int(book.select_one(".rating_rvCount > a > em.txC_blue").text.replace(",", "")) if book.select_one(".rating_rvCount > a > em.txC_blue") != None else 0
    values = (book_title, author, publisher, pub_date,  price, rating, n_reviews)
    for key, value in zip(keys, values):
        result.setdefault(key, []).append(value)

df = pd.DataFrame(result)
df

1/24
2/24
3/24
4/24
5/24
6/24
7/24
8/24
9/24
10/24
11/24
12/24
13/24
14/24
15/24
16/24
17/24
18/24
19/24
20/24
21/24
22/24
23/24
24/24

,제목,저자,출판사,출간일,가격,평점,리뷰수
0,트렌드 코리아 2026,"김난도, 전미영, 최지혜, 권정윤, 한다혜 외 7명 ...",미래의창,2025년 09월,18000,9.5,65
1,사탄탱고,크러스너호르커이 라슬로 /조원규,알마,2018년 05월,17820,9.1,27
2,절창 切創,구병모,문학동네,2025년 09월,16200,9.4,109
3,위버멘쉬,프리드리히 니체,떠오름,2025년 03월,16020,9.5,422
4,머니 트렌드 2026,"김도윤, 정태익, 김광석, 김승주, 김용섭 외 3명 ...",북모먼트,2025년 09월,23400,9.5,52
5,박곰희 연금 부자 수업,박곰희,인플루엔셜,2025년 06월,18900,9.7,143
6,다크 심리학,다크 사이드 프로젝트,어센딩,2025년 07월,19710,9.6,85
7,비트코인 없는 미래는 없다,"오태민, 손혜민, 김유정",거인의정원,2025년 09월,27900,9.9,67
8,손자병법,손자 /소준섭,현대지성,2025년 10월,11700,9.9,66
9,어른의 행복은 조용하다,태수,페이지2북스,2024년 11월,16020,9.5,369
10,ETF 투자의 모든 것,문일호,매일경제신문사,2025년 08월,18900,9.9,35
11,포즈랑의 투자 이야기,포즈랑,에디터,2025년 10월,19800,10.0,4
12,호의에 대하여,문형배,김영사,2025년 08월,16920,9.5,166
13,아무도 오지 않는 곳에서,천선란,허블,2025년 10월,15300,10.0,4
14,흔한남매 20,흔한남매 원/백난도 글/유난희 그림/흔한컴퍼니 감수,미래엔아이세움,2025년 09월,15120,9.9,136
15,류수영의 평생 레시피,류수영,세미콜론,2025년 06월,22500,9.7,279
16,렛뎀 이론,멜 로빈스 /윤효원,비즈니스북스,2025년 08월,18000,9.7,167
17,시대예보: 경량문명의 탄생,송길영,교보문고,2025년 09월,19800,9.4,19
18,돈의 심리학 (30만 부 기념 스페셜 에디션),모건 하우절 /이지연,인플루엔셜,2021년 01월,17820,9.4,1174
19,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,2025년 03월,18000,9.8,195
20,원피스 ONE PIECE 112,오다 에이이치로 글그림,대원,2025년 10월,5400,0.0,0
21,혼모노,성해나,창비,2025년 03월,16200,9.1,586
22,조용한 회복,박재연,한빛라이프,2025년 09월,19800,9.8,20
23,청춘의 필사,김종원,퍼스트펭귄,2025년 09월,19800,9.5,20

1. 베스트셀러 전체 책 가져오기
2. 저자/역자 구분하기
3. 저자가 여러명일 경우 저자 모두 추출해서 가져오기
4. 원저, 그림, 역자, 감수 가 있을 경우에도 모두 분리하기
5. 책 상세페이지 링크도 수집
-----------------------------------------------------------
1. 상세페이지로 들어가 품목정보에서 페이지수 추출
2. 카테고리 분류 내용 가져오기
3. 책소개 글 가져오기

In [104]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [106]:
author_list = []

for page in range(1,10):
    url = "https://www.yes24.com/product/category/bestseller"
    payload = dict(categoryNumber="001", pageNumber=page, pageSize=120)
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = bs(r.content, 'lxml')
    book_list = response.select("#yesBestList > li")
    print(f"{page+1}/9 페이지 수집중                 ")
    
    for idx, book in enumerate(book_list):
        print(f"{idx+1}/{len(book_list)} 자료 수집중", end="\r")
        result = dict(책제목="", 저 = "", 원저 = "", 글 = "", 역 = "", 글그림 = "", 사진 = "", 감수="",
                            그림 = "", 공저 = "", 기획="")
        result['책제목'] = book.select_one(".gd_name").text
        # 저자추출
        if "/" not in book.select_one(".authPub.info_auth").text:
            result['저'] = text_clean(book.select_one(".authPub.info_auth").text) 
        elif "/" in book.select_one(".authPub.info_auth").text:
            n_item = len(book.select_one(".authPub.info_auth").text.split("/"))
            items = book.select_one(".authPub.info_auth").text.split("/")
    #         print(idx, n_item, items, end="\n\n")
            if n_item == 2 and "정보 더 보기" in items[0]:
                result['저'] = text_clean(book.select_one(".moreAuthLiCont").text.replace("\n", " "))
            elif n_item >= 2 and "정보 더 보기" not in items[0]:
                for item in items:
    #                 print(item.split()[-1])
                    author_key = item.split()[-1]
                    result[author_key] = " ".join(item.split()[:-1])


        result['출판사'] = book.select_one(".authPub.info_pub > a").text
        result['출간일'] = book.select_one(".authPub.info_date").text
        result['가격'] = int(book.select_one(".yes_b").text.replace(",", ""))
        result['평점'] = float(book.select_one(".rating_grade > .yes_b").text) if book.select_one(".rating_grade > .yes_b") != None else 0
        result['리뷰수'] = int(text_clean(book.select_one(".rating_rvCount > a > em.txC_blue").text)) if book.select_one(".rating_rvCount > a > em.txC_blue") != None else 0
        result['상세링크'] = "https://www.yes24.com"+ book.select_one(".info_row.info_name > .gd_name")['href']

        author_list.append(result)
    
    time.sleep(3)
    
    
    
df = pd.DataFrame(author_list)
df

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200
2/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=2&pageSize=120
200
3/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=3&pageSize=120
200
4/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=4&pageSize=120
200
5/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=5&pageSize=120
200
6/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=6&pageSize=120
200
7/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=7&pageSize=120
200
8/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=8&pageSize=120
200
9/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=9&pageSize=120
200
10/9 페이지 수집중

,책제목,저,원저,글,역,글그림,사진,감수,그림,공저,...,평점,리뷰수,상세링크,편,편저,편역,해설,보기,분과,등저
0,트렌드 코리아 2026,김난도 전미영 최지혜 권정윤 한다혜 이혜원 이수진 서유현 전다현 이준영 이향은 김나은,,,,,,,,,...,9.5,66,https://www.yes24.com/product/goods/153064968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,사탄탱고,크러스너호르커이 라슬로,,,조원규,,,,,,...,9.1,27,https://www.yes24.com/product/goods/60543924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,절창 切創,구병모,,,,,,,,,...,9.4,109,https://www.yes24.com/product/goods/153497469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,위버멘쉬,프리드리히 니체,,,,,,,,,...,9.5,422,https://www.yes24.com/product/goods/142972546,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,머니 트렌드 2026,김도윤 정태익 김광석 김승주 김용섭 김학렬 김현준 최재붕,,,,,,,,,...,9.5,52,https://www.yes24.com/product/goods/152645689,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,백년목2 치료편,정선근,,,,,,,,,...,9.8,35,https://www.yes24.com/product/goods/129099339,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,행동력 수업,오현호,,,,,,,,,...,9.6,55,https://www.yes24.com/product/goods/128591149,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,포스 윙,레베카 야로스,,,이수현,,,,,,...,9.7,254,https://www.yes24.com/product/goods/127934853,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,역사를 보다,박현도 곽민수 강인욱 허준,,,,,,,,,...,9.6,99,https://www.yes24.com/product/goods/127047306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,율의 시선,김민서,,,,,,,,,...,9.6,249,https://www.yes24.com/product/goods/126190623,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
df

,저,원저,글,역,글그림,사진,감수,그림,공저,기획,출판사,출간일,가격,평점,리뷰수,상세링크
0,김난도 전미영 최지혜 권정윤 한다혜 이혜원 이수진 서유현 전다현 이준영 이향은 김나은,,,,,,,,,,미래의창,2025년 09월,18000,9.5,66,https://www.yes24.com/product/goods/153064968
1,크러스너호르커이 라슬로,,,조원규,,,,,,,알마,2018년 05월,17820,9.1,27,https://www.yes24.com/product/goods/60543924
2,구병모,,,,,,,,,,문학동네,2025년 09월,16200,9.4,109,https://www.yes24.com/product/goods/153497469
3,프리드리히 니체,,,,,,,,,,떠오름,2025년 03월,16020,9.5,422,https://www.yes24.com/product/goods/142972546
4,김도윤 정태익 김광석 김승주 김용섭 김학렬 김현준 최재붕,,,,,,,,,,북모먼트,2025년 09월,23400,9.5,52,https://www.yes24.com/product/goods/152645689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,한국데이터진흥원,,,,,,,,,,한국데이터산업진흥원,2023년 12월,17460,9.3,116,https://www.yes24.com/product/goods/124645703
116,헤르만 헤세,,,전영애,,,,,,,민음사,2000년 12월,7200,9.3,1097,https://www.yes24.com/product/goods/176787
117,신영준 고영성 편,,,,,,,,,,상상스퀘어,2025년 10월,22500,8.0,4,https://www.yes24.com/product/goods/155115043
118,최태성,,,,,,,,,,이투스북,2024년 12월,17550,9.9,174,https://www.yes24.com/product/goods/140231250
119,후지모토 타츠키 글그림,,,,,,,,,,학산문화사,2021년 09월,5400,9.9,267,https://www.yes24.com/product/goods/110692031