# Selenium 이란?
* 웹브라우저를 자동으로 제어하는 라이브러리
* 원래 다양한 웹브라우저를 자동으로 테스트하는 도구
* 코드를 통해 웹브라우저 조작 가능
* 동적 웹사이트에서 정보를 가져오는 활용
* https://www.selenium.dev/documentation/webdriver/

In [5]:
# !pip install selenium
# !pip install webdriver-manager

In [6]:
import selenium
print(selenium.__version__)

4.36.0

In [7]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

# 웹브라우저를 실행 할 때 사용할 옵션 - 사람인 것처럼 정보 입력
options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/141.0.0.0")
options.add_argument("lang=ko_KR")


driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )
# 웹브라우저에서 url 열기
driver.get("https://search.shopping.naver.com/book/search?bookTabType=ALL&pageIndex=1&pageSize=40&prevQuery=%EB%84%A4%EC%9D%B4%EB%B2%84%EB%8F%84%EC%84%9C&query=%ED%95%80%ED%85%8C%ED%81%AC&sort=REL")

In [9]:
search_box = driver.find_element(By.CSS_SELECTOR, "._searchInput_search_text_83jy9._nlog_click")
search_box.clear()

In [10]:
search_box.send_keys("파이썬")

In [11]:
search_box.send_keys(Keys.ENTER)

In [15]:
search_box = driver.find_element(By.CSS_SELECTOR, "._searchInput_search_text_83jy9._nlog_click")
search_box.clear()
search_box.send_keys("증권")
search_button = driver.find_element(By.CSS_SELECTOR, "._searchInput_button_search_wu9xq._nlog_click")
search_button.click()

# selenium에서 원하는 요소찾기
* driver.find_element(By.CSS_SELECTOR,css셀렉터): 1개 요소 찾기
* driver.find_elements(By.CSS_SELECTOR,css셀렉터): 여러개의 요소 찾기, list 반환
* driver.find_element(By.ID, "id"): html에서 id에 해당하는 태그 찾아줌
* driver.find_element(By.LINK_TEXT, "link에 포함된 문자"): link에 포함된 문자 찾기
* driver.find_element(By.PARTIAL_LINK_TEXT, "link에 포함된 일부 문자"): link에 포함된 문자 찾기

In [21]:
# 찾은 태그 안쪽 html 출력 .get_attribute('innerHTML')
driver.find_element(By.CSS_SELECTOR, ".bookListItem_title__1mWGq").get_attribute('innerHTML')

'<span class="bookListItem_text__oxa7M"><span>주식투자 단기 트레이딩의 정석</span></span>'

In [19]:
# 찾은 태그 안쪽 html 출력 .get_attribute('outerHTML')
driver.find_element(By.CSS_SELECTOR, ".bookListItem_title__1mWGq").get_attribute('outerHTML')

'<div class="bookListItem_title__1mWGq"><span class="bookListItem_text__oxa7M"><span>주식투자 단기 트레이딩의 정석</span></span></div>'

In [22]:
# 책제목
title = driver.find_element(By.CSS_SELECTOR, ".bookListItem_title__1mWGq").text

'주식투자 단기 트레이딩의 정석'

In [25]:
# 저자
author= driver.find_element(By.CSS_SELECTOR, ".bookListItem_define_item__jqcW8 > span:nth-child(2)").text

In [30]:
# 출판사
publisher = driver.find_element(By.CSS_SELECTOR, ".bookListItem_detail_publish__SGgZN > span:nth-child(2)").text

In [32]:
# 출간일
pub_date = driver.find_element(By.CSS_SELECTOR, ".bookListItem_detail_date__6_wYJ").text

In [38]:
# 평점
rating = driver.find_element(By.CSS_SELECTOR, ".bookListItem_grade__e60mi").text.split()[0][2:]

In [42]:
# 리뷰수
n_reviews = driver.find_element(By.CSS_SELECTOR, ".bookListItem_grade__e60mi").text.split()[1].replace("(", "").replace(")", "")

In [46]:
# 가격
price = int(driver.find_element(By.CSS_SELECTOR, ".bookPrice_price__Nv4Ee > em").text.replace(",", ""))

In [52]:
title = [titles.text for titles in driver.find_elements(By.CSS_SELECTOR, ".bookListItem_title__1mWGq")]
title

['주식투자 단기 트레이딩의 정석',
 '벤저민 그레이엄의 증권분석',
 'ETF 투자의 모든 것 (배당수익과 주가수익 다 잡는 제2의 소득 파이프라인)',
 '트레이딩의 전설 (실전투자대회 수상자 9인을 만나다)',
 '한국의 미래 (거대한 변곡점, 마지막 부의 기회를 잡아라)',
 '단 3개의 미국 ETF로 은퇴하라 (원하는 삶을 앞당기는 돈 자동 사냥 시스템)',
 '워런 버핏 바이블: 완결판 (버핏이 직접 말해주는 투자와 경영, 삶의 지혜: 1983~2025)',
 '주식 투자의 기쁨 (89세 현역 트레이더 시게루 할아버지의 흔들리지 않는 투자 철학)',
 '주식투자 단기 트레이딩의 정석 (25년 투자 고수가 전하는 매일 수익 내는 단타 매매의 기술)',
 '투자디톡스 + 필사노트 세트 (본성에 휘둘리지 않고 불안에서 벗어나기)']

# 네이버 책 데이터 수집하기

In [79]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

# 웹브라우저를 실행 할 때 사용할 옵션 - 사람인 것처럼 정보 입력
options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/141.0.0.0")
options.add_argument("lang=ko_KR")


driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )

keyword = input("검색어를 입력하세요:  ")
# 웹브라우저에서 url 열기
book_info_list = {}
for page in range(1, 11):
    driver.get(f"https://search.shopping.naver.com/book/search?bookTabType=ALL&pageIndex={page}&pageSize=40&prevQuery={keyword}&query={keyword}&sort=REL")

    # 전체 40개 데이터를 얻기 위해서 마우스 스크롤
    for scroll in range(0, 8001, 1000):
        driver.execute_script(f"window.scrollTo({0}, {scroll})")
        time.sleep(2)

    book_list = driver.find_elements(By.CSS_SELECTOR, ".list_book > li")
    for book in book_list:
        # 책제목
        title = book.find_element(By.CSS_SELECTOR, ".bookListItem_title__1mWGq").text

        try:
            # 저자
            author= book.find_element(By.CSS_SELECTOR, ".bookListItem_define_item__jqcW8 > span:nth-child(2)").text
        except:
            author= ""
        try:
            # 출판사
            publisher = book.find_element(By.CSS_SELECTOR, ".bookListItem_detail_publish__SGgZN > span:nth-child(2)").text
        except:
            publisher = ""
        try:
            # 출간일
            pub_date = book.find_element(By.CSS_SELECTOR, ".bookListItem_detail_date__6_wYJ").text
        except:
            pub_date = ""
        try:
            # 평점
            rating = book.find_element(By.CSS_SELECTOR, ".bookListItem_grade__e60mi").text.split()[0][2:]
        except:
            rating = 0
        try:
            # 리뷰수
            n_reviews = book.find_element(By.CSS_SELECTOR, ".bookListItem_grade__e60mi").text.split()[1].replace("(", "").replace(")", "") if book.find_element(By.CSS_SELECTOR, ".bookListItem_grade__e60mi") != None else 0
        except:
            n_reviews = 0
        try:
            # 가격
            price = int(book.find_element(By.CSS_SELECTOR, ".bookPrice_price__Nv4Ee > em").text.replace(",", "")) 
        except:
            price = 0

        keys = ['책제목', '저자', '출판사', '출간일', '평점', '리뷰수', '가격']
        book_info = (title, author, publisher, pub_date, rating, n_reviews, price)

        for key, value in zip(keys, book_info):
            book_info_list.setdefault(key, []).append(value)

driver.close()            
            
df = pd.DataFrame(book_info_list)
df

검색어를 입력하세요:  파이썬

,책제목,저자,출판사,출간일,평점,리뷰수,가격
0,파이썬 디자인 패턴 2/e (디자인 패턴을 사용해 소프트웨어 설계 문제 해결하기),체탄 기리다,에이콘출판,2018.11.30.,0,0,13500
1,"자료구조와 알고리즘 with 파이썬 (수강생이 궁금해하고, 어려우하는 내용을 가장 ...",최영규,생능북스,2023.11.20.,5.0,1,21600
2,"전문가를 위한 파이썬 (파이썬3 버전 기준 | 간단하고, 명료하고, 효율적인 파이썬...",루시아누 하말류,한빛미디어,2016.08.12.,4.5,2,49500
3,파이썬으로 배우는 공업수학,"김도영, 김재현 외 3명",지오북스,2022.03.01.,0,0,0
4,파이썬 핵심 레퍼런스 (빠르게 찾아서 바로 적용하는 실무가이드 | 파이썬 3.4와 ...,마크 루츠,인사이트,2016.08.12.,0,0,15120
5,마인크래프트로 배우는 파이썬 입문,주식회사 Nuco 카지마 유헤이,에이케이커뮤니케이션즈,2023.11.25.,5.0,1,14220
6,"파이썬 네트워크 프로그래밍 (사물인터넷을 위한, 제3판)","서열규, 전희성",복두출판사,2022.02.25.,0,0,25200
7,파이썬 프로그래밍 길라잡이,장혜진,홍릉,2022.02.25.,0,0,27550
8,파이썬과 수치 해석 2/e (파이썬 수치 해석 레시피),로버트 요한슨,에이콘출판,2019.08.30.,0,0,45000
9,파이썬으로 제어하는 마이크로비트 개정판 (개정판),북마크,부크크(bookk),2025.01.02.,0,0,10900
10,파이썬 웹 프로그래밍 (플라스크를 이용한 쉽고 빠른 웹 개발),주성식,위키북스,2016.05.31.,0,0,25000
11,쓸모 있는 파이썬 프로그램 40개 (나도 모르게 파이썬에 홀딱 빠지는),심교훈,로드북,2023.06.20.,5.0,1,27000
12,파이썬을 이용한 수치해석,"류권규, 이남주",씨아이알,2020.12.28.,0,0,31500
13,"데이터 과학을 위한 파이썬과 R (오픈소스를 활용한 데이터 분석, 시각화, 머신러닝...","Scavetta, Rick J., Angelov, Boyan",한빛미디어,2022.10.28.,0,0,16200
14,처음 시작하는 파이썬 (파이썬 패키지를 활용한 모던 컴퓨팅 입문),빌 루바노빅,한빛미디어,2015.12.10.,0,0,0
15,파이썬으로 배우는 인공지능 수학,"이재광, 전태일",인피니티북스,2023.03.01.,0,0,28800
16,기계학습 기반의 파이썬 활용,"황철현, 정회경",성진미디어,2021.11.30.,0,0,17100
17,파이썬으로 배우는 과학계산,김웅태,서울대학교출판문화원,2021.12.31.,5.0,1,33250
18,파이썬을 활용한 베이지안 통계 (동전 던지기부터 월드컵까지 다양하게 배우는 데이터 분석),앨런 B. 다우니,한빛미디어,2022.06.30.,5.0,3,20520
19,머신러닝 리스크 관리 with 파이썬 (안정성과 신뢰성 높은 견고한 모델을 구축하는...,"패트릭 홀포드, 제임스 커티스 외 1명",한빛미디어,2024.05.10.,0,0,37800
20,"파이썬 마이크로서비스 (모범 사례로 알아보는 파이썬 마이크로서비스 개발, 테스트, ...",타렉 지아드,에이콘출판,2019.05.17.,0,0,31500
21,파이썬 웹프로그래밍 (Django(장고)로 배우는 쉽고 빠른 웹개발),김석훈,한빛미디어,2015.04.01.,0,0,0
22,따라하며 배우는 파이썬과 데이터 과학 (파이썬으로 시작하는 데이터 과학과 기계학습),"천인국, 박동규 외 1명",생능출판,2023.11.20.,4.73,11,26680
23,인공지능과 함께하는 파이썬,"복거철, 정회경",성진미디어,2021.11.30.,4.0,2,14250
24,프로그래머를 위한 파이썬 (실전 프로젝트로 배우는 소프트웨어 개발의 원리와 정석),데인 힐라드,제이펍,2020.11.13.,5.0,1,22500
25,파이썬다운 코드를 개발하는 63가지 실용 기법,용 추이(Yong Cui),인사이트,2025.08.20.,0,0,34200
26,"파이썬 더 쉽게, 더 깊게 (친절한 설명과 다양한 예제로 배우는)",츠지 신고,제이펍,2014.09.17.,0,0,26000
27,프로그래밍 레벨업 파이썬 활용,조현준,북스홀릭퍼블리싱,2022.08.29.,0,0,0
28,"예제로 배우는 파이썬 머신러닝 (텐서플로 2, 파이토치, 사이킷런으로)",위시 (헤이든) 류,제이펍,2022.08.26.,0,0,29700
29,파이썬 데이터 과학 통계 학습 (Python Data Science Statisti...,"황보현우, 정지현",정보문화사,2021.05.25.,0,0,26100
30,예제부터 배우는 거꾸로 파이썬 (투자 로또 리뷰 등 6가지 유용한 주제로 시작하는 ...,구재홍,비제이퍼블릭,2022.08.19.,5.0,1,20700
31,그림과 함께하는 파이썬 수업,"최윤철, 임순범",생능출판,2021.11.03.,0,0,25760
32,"실리콘밸리에서 통하는 파이썬 인터뷰 가이드 (취업과 이직을 위한 자료구조, 알고리즘...","런젠펑, 취안수쉐",제이펍,2025.05.06.,0,0,24300
33,파이썬 웹 프로그래밍 (플라스크를 이용한 쉽고 빠른 웹 개발),주성식,위키북스,2014.01.28.,0,0,0
34,디지털 시대의 설득 언어 : 파이썬 데이터 시각화,조상철,퍼플,2025.05.26.,0,0,26000
35,파이썬 for Beginner (쉽고 빠르게 익히는 프로그래밍의 기본 원리),우재남,한빛아카데미,2022.01.03.,4.71,14,23000
36,파이썬 웹 스크래핑 2/e (수많은 데이터 사이에서 필요한 정보 수집하기),"캐서린 자멀, 리차드 로손",에이콘출판,2018.12.31.,0,0,22500
37,가즈아! 파이썬 세상으로,,연두에디션,2018.12.20.,0,0,19000
38,"파이썬 성능 높이기 2/e (프로그램 병목 찾기부터 파이썬 구현 선택, 병렬 시스템...",가브리엘레 라나로,에이콘출판,2018.11.30.,0,0,25200
39,마이크로파이썬을 활용한 사물인터넷 (챗GPT로 코딩하기),양재삼,한빛아카데미,2025.01.02.,0,0,25760

,책제목,저자,출판사,출간일,평점,리뷰수,가격
0,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),박응용,이지스퍼블리싱,2023.06.15.,4.96,84,19800
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),윤인성,한빛미디어,2022.06.01.,4.91,23,19800
2,파이썬,홍의경,생능출판,2022.03.09.,0,0,29440
3,독학 파이썬,야마다 요시히로,정보문화사,2024.12.20.,0,0,28800
4,파이썬 (제2판),"염기원, 오지영",북두,2022.01.20.,0,0,16200
5,으뜸 파이썬 (개정판),"박동규, 강영민",생능출판,2024.06.14.,4.6,10,30600
6,파이썬,염기원,복두출판사,2020.08.20.,0,0,13500
7,파이썬,김영천,기한재,2020.02.25.,0,0,23000
8,파이썬 (비전공자를위한 파이썬 기초 입문서),김명호,에듀웨이,2019.05.25.,0,0,16200
9,파이썬,"이정환, 신항식 외 2명",도서출판 홍릉(홍릉과학출판사),2019.09.02.,0,0,23750
10,파이썬 + AI (코드조각과 실행화면으로 배우는 코딩),"안용제, 김남규",디지털북스,2024.07.15.,5.0,1,23940
11,파이썬 (다양한 예제로 알로리즘 쉽게 분석하기),김유진,다본,2019.04.10.,0,0,22500
12,파이썬,"서정원, 김태령",생능출판,2019.02.28.,0,0,0
13,파이썬 마스터 (실생활 융합 예제로 배우는),"김종훈, 김동건",한빛아카데미,2025.01.17.,5.0,3,29440
14,파이썬,Y. Daniel Liang,에피스테메,2018.03.02.,0,0,31500
15,파이썬,천인국,인피니티북스,2017.08.30.,0,0,10800
16,파이썬 플러스,최희식,인피니티북스,2024.07.31.,5.0,1,22500
17,내공의 파이썬 (한 권으로 끝내는 초보자용 코딩 입문서),한선관,자유아카데미,2025.03.15.,0,0,24840
18,파이썬 (컴퓨팅 사고력을 키우는 SW 교육),우재남,한빛아카데미,2016.07.20.,0,0,20460
19,파이썬,Y. Daniel Liang,생능출판,2016.02.05.,0,0,0
20,파이썬 워크북,안기수,생능출판,2025.01.15.,0,0,13500
21,엑셀X파이썬 (엑셀이 파이썬을 품었다),정성일,길벗,2024.07.30.,0,0,21375
22,파이썬컴퓨팅,"한종대, 민경하 외 1명",한국방송통신대학교출판문화원,2024.07.25.,0,0,14910
23,이지파이썬 2 (그림과 스토리텔링으로 이해하는 쉽고 재미있는 파이썬),한국인공지능아카데미,클라우드북스,2024.09.01.,0,0,14400
24,이지파이썬 1 (그림과 스토리텔링으로 이해하는 쉽고 재미있는 파이썬),한국인공지능아카데미,클라우드북스,2024.09.01.,0,0,14400
25,이지파이썬 1 (그림과 스토리텔링으로 이해하는 쉽고 재미있는 파이썬),한국인공지능아카데미,클라우드북스,2024.09.01.,0,0,0
26,파이썬 강좌,류주환,퍼플,2023.03.27.,0,0,19000
27,파이썬데이터처리,"한종대, 민경하",한국방송통신대학교출판문화원,2025.07.25.,0,0,19300
28,파이썬 프로그래밍 (기초부터 딥러닝까지),허준,성안당,2025.03.12.,0,0,21375
29,"자기주도 파이썬 (혼자서도 쉽게 익힐 수 있는, 제4판)",한컴에듀케이션 알고리즘연구소,복두출판사,2024.08.05.,0,0,16560
30,파이썬 통계학 기초 (단계별 접근),"문창권, 박수용 외 2명",탐진출판사,2025.08.11.,0,0,31500
31,처음이야? 파이썬 기초 (동영상 강의로 배우는 292개 코드 따라하기(핵심노트+오픈...,"윤영빈, 오환 외 1명",영진닷컴,2025.06.20.,5.0,2,18000
32,파이썬 연습 (개정판),김기용,그린,2022.02.25.,5.0,1,23400
33,"안녕, 파이썬",김학인,북랩,2022.03.14.,5.0,1,16110
34,달구나 파이썬! (개정판),"노순국, 이금분 외 1명",연두에디션,2023.08.15.,5.0,1,18000
35,파이썬의 정석,"조용주, 임좌상",길벗캠퍼스,2023.01.10.,0,0,26820
36,파이썬 올인원 (기초부터 데이터분석까지),"이지민, 임희경",연두에디션,2023.09.04.,0,0,20700
37,두근두근 파이썬 (만들면서 배우는),천인국,생능출판,2023.01.05.,4.85,13,23000
38,파이썬 3 (프로그래밍을 배우기에 가장 재미있는 언어),박상현,한빛미디어,2016.02.10.,0,0,15750
39,클린 파이썬 (효과적인 파이썬 코딩 기법),수닐 카필,에이콘출판,2021.04.16.,0,0,19800