In [1]:
import os
import re
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup as bs
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
os.getenv("seoul_api")

'456e77634a6861723939436f4a6c76'

In [27]:
url = f"http://openapi.seoul.go.kr:8088/{os.getenv("seoul_api")}/json/VwsmAdstrdNcmCnsmpW/1/1000"
# payload = dict(KEY=os.getenv("seoul_api"), TYPE="json", SERVICE="VwsmAdstrdNcmCnsmpW", START_INDEX=1,  END_INDEX=5)
r = requests.get(url)
print(r.url)
print(r.status_code)
response = r.json()
response

http://openapi.seoul.go.kr:8088/456e77634a6861723939436f4a6c76/json/VwsmAdstrdNcmCnsmpW/1/1000
200

{'VwsmAdstrdNcmCnsmpW': {'list_total_count': 11050,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'STDR_YYQU_CD': '20241',
    'ADSTRD_CD': '11545690',
    'ADSTRD_CD_NM': '시흥3동',
    'MT_AVRG_INCOME_AMT': 2516251.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 501526000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 123149000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 1842000.0,
    'LVSPL_EXPNDTR_TOTAMT': 25596000.0,
    'MCP_EXPNDTR_TOTAMT': 17315000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 189462000.0,
    'EDC_EXPNDTR_TOTAMT': 7185000.0,
    'PLESR_EXPNDTR_TOTAMT': 19648000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 14380000.0,
    'ETC_EXPNDTR_TOTAMT': 9216000.0,
    'FD_EXPNDTR_TOTAMT': 93733000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11110530',
    'ADSTRD_CD_NM': '사직동',
    'MT_AVRG_INCOME_AMT': 5208463.0,
    'INCOME_SCTN_CD': '09',
    'EXPNDTR_TOTAMT': 31889341000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1238314000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 158974000.0,
    'LVSPL_EXPNDTR_TOTAMT': 60281000.0,
    'MCP_EXPNDTR_TOTAMT': 586427000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 188458000.0,
    'EDC_EXPNDTR_TOTAMT': 169234000.0,
    'PLESR_EXPNDTR_TOTAMT': 293797000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 1241791000.0,
    'ETC_EXPNDTR_TOTAMT': 23670438000.0,
    'FD_EXPNDTR_TOTAMT': 4281627000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11110615',
    'ADSTRD_CD_NM': '종로1·2·3·4가동',
    'MT_AVRG_INCOME_AMT': 3350350.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 77584610000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 3618998000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 7478066000.0,
    'LVSPL_EXPNDTR_TOTAMT': 861970000.0,
    'MCP_EXPNDTR_TOTAMT': 4123252000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 3236609000.0,
    'EDC_EXPNDTR_TOTAMT': 2062644000.0,
    'PLESR_EXPNDTR_TOTAMT': 2398515000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 13520753000.0,
    'ETC_EXPNDTR_TOTAMT': 23729021000.0,
    'FD_EXPNDTR_TOTAMT': 16554782000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11110650',
    'ADSTRD_CD_NM': '혜화동',
    'MT_AVRG_INCOME_AMT': 3472006.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 7826497000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1354887000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 215665000.0,
    'LVSPL_EXPNDTR_TOTAMT': 77222000.0,
    'MCP_EXPNDTR_TOTAMT': 1129580000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 20145000.0,
    'EDC_EXPNDTR_TOTAMT': 195279000.0,
    'PLESR_EXPNDTR_TOTAMT': 415196000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 565923000.0,
    'ETC_EXPNDTR_TOTAMT': 361926000.0,
    'FD_EXPNDTR_TOTAMT': 3490674000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11110680',
    'ADSTRD_CD_NM': '창신2동',
    'MT_AVRG_INCOME_AMT': 2179485.0,
    'INCOME_SCTN_CD': '05',
    'EXPNDTR_TOTAMT': 670987000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 143195000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 23323000.0,
    'LVSPL_EXPNDTR_TOTAMT': 11149000.0,
    'MCP_EXPNDTR_TOTAMT': 142754000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 945000.0,
    'EDC_EXPNDTR_TOTAMT': 0.0,
    'PLESR_EXPNDTR_TOTAMT': 17411000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 32513000.0,
    'ETC_EXPNDTR_TOTAMT': 18104000.0,
    'FD_EXPNDTR_TOTAMT': 281593000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11140520',
    'ADSTRD_CD_NM': '소공동',
    'MT_AVRG_INCOME_AMT': 5583264.0,
    'INCOME_SCTN_CD': '09',
    'EXPNDTR_TOTAMT': 1018122360000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 21939934000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 79342000.0,
    'LVSPL_EXPNDTR_TOTAMT': 398705000.0,
    'MCP_EXPNDTR_TOTAMT': 1374288000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 13670278000.0,
    'EDC_EXPNDTR_TOTAMT': 412044000.0,
    'PLESR_EXPNDTR_TOTAMT': 200962000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 965779543000.0,
    'ETC_EXPNDTR_TOTAMT': 11607102000.0,
    'FD_EXPNDTR_TOTAMT': 2660162000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11140635',
    'ADSTRD_CD_NM': '약수동',
    'MT_AVRG_INCOME_AMT': 4018057.0,
    'INCOME_SCTN_CD': '08',
    'EXPNDTR_TOTAMT': 2413605000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 932147000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 68708000.0,
    'LVSPL_EXPNDTR_TOTAMT': 132810000.0,
    'MCP_EXPNDTR_TOTAMT': 342100000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 7030000.0,
    'EDC_EXPNDTR_TOTAMT': 99207000.0,
    'PLESR_EXPNDTR_TOTAMT': 47219000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 221430000.0,
    'ETC_EXPNDTR_TOTAMT': 101172000.0,
    'FD_EXPNDTR_TOTAMT': 461782000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11140680',
    'ADSTRD_CD_NM': '중림동',
    'MT_AVRG_INCOME_AMT': 4531982.0,
    'INCOME_SCTN_CD': '08',
    'EXPNDTR_TOTAMT': 1950873000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 237716000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 20367000.0,
    'LVSPL_EXPNDTR_TOTAMT': 62182000.0,
    'MCP_EXPNDTR_TOTAMT': 321546000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 5243000.0,
    'EDC_EXPNDTR_TOTAMT': 39152000.0,
    'PLESR_EXPNDTR_TOTAMT': 55433000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 158417000.0,
    'ETC_EXPNDTR_TOTAMT': 273045000.0,
    'FD_EXPNDTR_TOTAMT': 777772000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11170590',
    'ADSTRD_CD_NM': '용문동',
    'MT_AVRG_INCOME_AMT': 3668097.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 1064672000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 409041000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 40475000.0,
    'LVSPL_EXPNDTR_TOTAMT': 23079000.0,
    'MCP_EXPNDTR_TOTAMT': 70261000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 811000.0,
    'EDC_EXPNDTR_TOTAMT': 71451000.0,
    'PLESR_EXPNDTR_TOTAMT': 62220000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 50376000.0,
    'ETC_EXPNDTR_TOTAMT': 35630000.0,
    'FD_EXPNDTR_TOTAMT': 301328000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11170650',
    'ADSTRD_CD_NM': '이태원1동',
    'MT_AVRG_INCOME_AMT': 3735055.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 9078226000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 910426000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 379341000.0,
    'LVSPL_EXPNDTR_TOTAMT': 175194000.0,
    'MCP_EXPNDTR_TOTAMT': 175056000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 14129000.0,
    'EDC_EXPNDTR_TOTAMT': 27679000.0,
    'PLESR_EXPNDTR_TOTAMT': 1677163000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 565289000.0,
    'ETC_EXPNDTR_TOTAMT': 280828000.0,
    'FD_EXPNDTR_TOTAMT': 4873121000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11200560',
    'ADSTRD_CD_NM': '행당1동',
    'MT_AVRG_INCOME_AMT': 3700164.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 6250391000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 583160000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 178560000.0,
    'LVSPL_EXPNDTR_TOTAMT': 127506000.0,
    'MCP_EXPNDTR_TOTAMT': 858305000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 66276000.0,
    'EDC_EXPNDTR_TOTAMT': 454004000.0,
    'PLESR_EXPNDTR_TOTAMT': 95362000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 892823000.0,
    'ETC_EXPNDTR_TOTAMT': 492372000.0,
    'FD_EXPNDTR_TOTAMT': 2502023000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11200570',
    'ADSTRD_CD_NM': '행당2동',
    'MT_AVRG_INCOME_AMT': 4593947.0,
    'INCOME_SCTN_CD': '08',
    'EXPNDTR_TOTAMT': 1396123000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 467401000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 18708000.0,
    'LVSPL_EXPNDTR_TOTAMT': 1483000.0,
    'MCP_EXPNDTR_TOTAMT': 174176000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 0.0,
    'EDC_EXPNDTR_TOTAMT': 260969000.0,
    'PLESR_EXPNDTR_TOTAMT': 5737000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 161485000.0,
    'ETC_EXPNDTR_TOTAMT': 59965000.0,
    'FD_EXPNDTR_TOTAMT': 246199000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11200790',
    'ADSTRD_CD_NM': '용답동',
    'MT_AVRG_INCOME_AMT': 2514752.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 5635841000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 731480000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 92171000.0,
    'LVSPL_EXPNDTR_TOTAMT': 29924000.0,
    'MCP_EXPNDTR_TOTAMT': 1320703000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 2077501000.0,
    'EDC_EXPNDTR_TOTAMT': 69649000.0,
    'PLESR_EXPNDTR_TOTAMT': 190295000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 133029000.0,
    'ETC_EXPNDTR_TOTAMT': 168699000.0,
    'FD_EXPNDTR_TOTAMT': 822390000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11215850',
    'ADSTRD_CD_NM': '구의1동',
    'MT_AVRG_INCOME_AMT': 2829119.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 3416072000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 660647000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 150050000.0,
    'LVSPL_EXPNDTR_TOTAMT': 77338000.0,
    'MCP_EXPNDTR_TOTAMT': 360281000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 64959000.0,
    'EDC_EXPNDTR_TOTAMT': 61145000.0,
    'PLESR_EXPNDTR_TOTAMT': 365178000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 153877000.0,
    'ETC_EXPNDTR_TOTAMT': 91099000.0,
    'FD_EXPNDTR_TOTAMT': 1431498000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11230660',
    'ADSTRD_CD_NM': '장안2동',
    'MT_AVRG_INCOME_AMT': 3106817.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 9607098000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1838198000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 2036300000.0,
    'LVSPL_EXPNDTR_TOTAMT': 231471000.0,
    'MCP_EXPNDTR_TOTAMT': 1143187000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 164944000.0,
    'EDC_EXPNDTR_TOTAMT': 529416000.0,
    'PLESR_EXPNDTR_TOTAMT': 497014000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 540959000.0,
    'ETC_EXPNDTR_TOTAMT': 185813000.0,
    'FD_EXPNDTR_TOTAMT': 2439796000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11230705',
    'ADSTRD_CD_NM': '청량리동',
    'MT_AVRG_INCOME_AMT': 2910130.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 3230583000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 764690000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 68344000.0,
    'LVSPL_EXPNDTR_TOTAMT': 70719000.0,
    'MCP_EXPNDTR_TOTAMT': 586194000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 312204000.0,
    'EDC_EXPNDTR_TOTAMT': 59498000.0,
    'PLESR_EXPNDTR_TOTAMT': 97486000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 235506000.0,
    'ETC_EXPNDTR_TOTAMT': 120315000.0,
    'FD_EXPNDTR_TOTAMT': 915627000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11260540',
    'ADSTRD_CD_NM': '면목4동',
    'MT_AVRG_INCOME_AMT': 2652945.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 746712000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 263141000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 28162000.0,
    'LVSPL_EXPNDTR_TOTAMT': 15439000.0,
    'MCP_EXPNDTR_TOTAMT': 55306000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 4453000.0,
    'EDC_EXPNDTR_TOTAMT': 68114000.0,
    'PLESR_EXPNDTR_TOTAMT': 68487000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 23675000.0,
    'ETC_EXPNDTR_TOTAMT': 18393000.0,
    'FD_EXPNDTR_TOTAMT': 201542000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11260575',
    'ADSTRD_CD_NM': '면목3·8동',
    'MT_AVRG_INCOME_AMT': 2436947.0,
    'INCOME_SCTN_CD': '05',
    'EXPNDTR_TOTAMT': 3087089000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 815639000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 95108000.0,
    'LVSPL_EXPNDTR_TOTAMT': 26143000.0,
    'MCP_EXPNDTR_TOTAMT': 268340000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 4442000.0,
    'EDC_EXPNDTR_TOTAMT': 73742000.0,
    'PLESR_EXPNDTR_TOTAMT': 370734000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 309810000.0,
    'ETC_EXPNDTR_TOTAMT': 141763000.0,
    'FD_EXPNDTR_TOTAMT': 981368000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11320512',
    'ADSTRD_CD_NM': '창2동',
    'MT_AVRG_INCOME_AMT': 2667920.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 2484917000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 703005000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 46592000.0,
    'LVSPL_EXPNDTR_TOTAMT': 19991000.0,
    'MCP_EXPNDTR_TOTAMT': 643754000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 180237000.0,
    'EDC_EXPNDTR_TOTAMT': 138671000.0,
    'PLESR_EXPNDTR_TOTAMT': 101059000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 193623000.0,
    'ETC_EXPNDTR_TOTAMT': 78921000.0,
    'FD_EXPNDTR_TOTAMT': 379064000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11320513',
    'ADSTRD_CD_NM': '창3동',
    'MT_AVRG_INCOME_AMT': 2339110.0,
    'INCOME_SCTN_CD': '05',
    'EXPNDTR_TOTAMT': 934831000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 217842000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 11236000.0,
    'LVSPL_EXPNDTR_TOTAMT': 23686000.0,
    'MCP_EXPNDTR_TOTAMT': 112467000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 10547000.0,
    'EDC_EXPNDTR_TOTAMT': 40511000.0,
    'PLESR_EXPNDTR_TOTAMT': 68755000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 60595000.0,
    'ETC_EXPNDTR_TOTAMT': 61582000.0,
    'FD_EXPNDTR_TOTAMT': 327610000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11320670',
    'ADSTRD_CD_NM': '쌍문2동',
    'MT_AVRG_INCOME_AMT': 2526418.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 3795964000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 722700000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 94704000.0,
    'LVSPL_EXPNDTR_TOTAMT': 380434000.0,
    'MCP_EXPNDTR_TOTAMT': 304903000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 488690000.0,
    'EDC_EXPNDTR_TOTAMT': 198547000.0,
    'PLESR_EXPNDTR_TOTAMT': 136711000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 364578000.0,
    'ETC_EXPNDTR_TOTAMT': 242296000.0,
    'FD_EXPNDTR_TOTAMT': 862401000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11350619',
    'ADSTRD_CD_NM': '중계본동',
    'MT_AVRG_INCOME_AMT': 4408060.0,
    'INCOME_SCTN_CD': '08',
    'EXPNDTR_TOTAMT': 5201503000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1419786000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 115543000.0,
    'LVSPL_EXPNDTR_TOTAMT': 12227000.0,
    'MCP_EXPNDTR_TOTAMT': 252171000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 333990000.0,
    'EDC_EXPNDTR_TOTAMT': 1645360000.0,
    'PLESR_EXPNDTR_TOTAMT': 67520000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 413265000.0,
    'ETC_EXPNDTR_TOTAMT': 181890000.0,
    'FD_EXPNDTR_TOTAMT': 759751000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11350621',
    'ADSTRD_CD_NM': '중계1동',
    'MT_AVRG_INCOME_AMT': 4840224.0,
    'INCOME_SCTN_CD': '08',
    'EXPNDTR_TOTAMT': 3779138000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 503404000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 58085000.0,
    'LVSPL_EXPNDTR_TOTAMT': 282361000.0,
    'MCP_EXPNDTR_TOTAMT': 221661000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 29778000.0,
    'EDC_EXPNDTR_TOTAMT': 1658093000.0,
    'PLESR_EXPNDTR_TOTAMT': 17949000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 263711000.0,
    'ETC_EXPNDTR_TOTAMT': 59323000.0,
    'FD_EXPNDTR_TOTAMT': 684773000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11380552',
    'ADSTRD_CD_NM': '갈현2동',
    'MT_AVRG_INCOME_AMT': 2670588.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 5325839000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1542349000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 320511000.0,
    'LVSPL_EXPNDTR_TOTAMT': 15730000.0,
    'MCP_EXPNDTR_TOTAMT': 500900000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 52317000.0,
    'EDC_EXPNDTR_TOTAMT': 660101000.0,
    'PLESR_EXPNDTR_TOTAMT': 330909000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 283009000.0,
    'ETC_EXPNDTR_TOTAMT': 183322000.0,
    'FD_EXPNDTR_TOTAMT': 1436691000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11380600',
    'ADSTRD_CD_NM': '응암3동',
    'MT_AVRG_INCOME_AMT': 2467614.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 4894015000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1603079000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 183192000.0,
    'LVSPL_EXPNDTR_TOTAMT': 48671000.0,
    'MCP_EXPNDTR_TOTAMT': 559089000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 229522000.0,
    'EDC_EXPNDTR_TOTAMT': 143657000.0,
    'PLESR_EXPNDTR_TOTAMT': 464249000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 267318000.0,
    'ETC_EXPNDTR_TOTAMT': 135178000.0,
    'FD_EXPNDTR_TOTAMT': 1260060000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11410720',
    'ADSTRD_CD_NM': '북가좌2동',
    'MT_AVRG_INCOME_AMT': 2727933.0,
    'INCOME_SCTN_CD': '06',
    'EXPNDTR_TOTAMT': 2776685000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 834190000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 36031000.0,
    'LVSPL_EXPNDTR_TOTAMT': 266305000.0,
    'MCP_EXPNDTR_TOTAMT': 286439000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 26394000.0,
    'EDC_EXPNDTR_TOTAMT': 180523000.0,
    'PLESR_EXPNDTR_TOTAMT': 102754000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 106617000.0,
    'ETC_EXPNDTR_TOTAMT': 106596000.0,
    'FD_EXPNDTR_TOTAMT': 830836000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11440600',
    'ADSTRD_CD_NM': '대흥동',
    'MT_AVRG_INCOME_AMT': 3531112.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 4238273000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 732618000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 46077000.0,
    'LVSPL_EXPNDTR_TOTAMT': 161694000.0,
    'MCP_EXPNDTR_TOTAMT': 740157000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 8295000.0,
    'EDC_EXPNDTR_TOTAMT': 805696000.0,
    'PLESR_EXPNDTR_TOTAMT': 121879000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 344680000.0,
    'ETC_EXPNDTR_TOTAMT': 250118000.0,
    'FD_EXPNDTR_TOTAMT': 1027059000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11440630',
    'ADSTRD_CD_NM': '신수동',
    'MT_AVRG_INCOME_AMT': 4157697.0,
    'INCOME_SCTN_CD': '08',
    'EXPNDTR_TOTAMT': 2341169000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 559399000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 13048000.0,
    'LVSPL_EXPNDTR_TOTAMT': 101649000.0,
    'MCP_EXPNDTR_TOTAMT': 724670000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 60322000.0,
    'EDC_EXPNDTR_TOTAMT': 141305000.0,
    'PLESR_EXPNDTR_TOTAMT': 54185000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 144365000.0,
    'ETC_EXPNDTR_TOTAMT': 30640000.0,
    'FD_EXPNDTR_TOTAMT': 511586000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11440700',
    'ADSTRD_CD_NM': '망원2동',
    'MT_AVRG_INCOME_AMT': 3070818.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 2646924000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 952481000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 46338000.0,
    'LVSPL_EXPNDTR_TOTAMT': 33338000.0,
    'MCP_EXPNDTR_TOTAMT': 156941000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 15059000.0,
    'EDC_EXPNDTR_TOTAMT': 136618000.0,
    'PLESR_EXPNDTR_TOTAMT': 131316000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 294287000.0,
    'ETC_EXPNDTR_TOTAMT': 57908000.0,
    'FD_EXPNDTR_TOTAMT': 822638000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11440710',
    'ADSTRD_CD_NM': '연남동',
    'MT_AVRG_INCOME_AMT': 3074384.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 6008344000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1284204000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 229858000.0,
    'LVSPL_EXPNDTR_TOTAMT': 153873000.0,
    'MCP_EXPNDTR_TOTAMT': 88348000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 30050000.0,
    'EDC_EXPNDTR_TOTAMT': 231504000.0,
    'PLESR_EXPNDTR_TOTAMT': 333539000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 176152000.0,
    'ETC_EXPNDTR_TOTAMT': 101966000.0,
    'FD_EXPNDTR_TOTAMT': 3378850000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11440740',
    'ADSTRD_CD_NM': '상암동',
    'MT_AVRG_INCOME_AMT': 4375860.0,
    'INCOME_SCTN_CD': '08',
    'EXPNDTR_TOTAMT': 26150673000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1305480000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 171356000.0,
    'LVSPL_EXPNDTR_TOTAMT': 14617000.0,
    'MCP_EXPNDTR_TOTAMT': 855450000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 92701000.0,
    'EDC_EXPNDTR_TOTAMT': 2152936000.0,
    'PLESR_EXPNDTR_TOTAMT': 186300000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 17522584000.0,
    'ETC_EXPNDTR_TOTAMT': 461419000.0,
    'FD_EXPNDTR_TOTAMT': 3387830000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11470510',
    'ADSTRD_CD_NM': '목1동',
    'MT_AVRG_INCOME_AMT': 5831059.0,
    'INCOME_SCTN_CD': '09',
    'EXPNDTR_TOTAMT': 186359513000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 3708720000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 139699000.0,
    'LVSPL_EXPNDTR_TOTAMT': 92308000.0,
    'MCP_EXPNDTR_TOTAMT': 3711760000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 1601363000.0,
    'EDC_EXPNDTR_TOTAMT': 1759057000.0,
    'PLESR_EXPNDTR_TOTAMT': 347787000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 169387333000.0,
    'ETC_EXPNDTR_TOTAMT': 1407133000.0,
    'FD_EXPNDTR_TOTAMT': 4204353000.0},
   {'STDR_YYQU_CD': '20191',
    'ADSTRD_CD': '11470640',
    'ADSTRD_CD_NM': '신정3동',
    'MT_AVRG_INCOME_AMT': 3290614.0,
    'INCOME_SCTN_CD': '07',
    'EXPNDTR_TOTAMT': 3600829000.0,
    'FDSTFFS_EXPNDTR_TOTAMT': 1008755000.0,
    'CLTHS_FTWR_EXPNDTR_TOTAMT': 115300000.0,
    'LVSPL_EXPNDTR_TOTAMT': 235853000.0,
    'MCP_EXPNDTR_TOTAMT': 926124000.0,
    'TRNSPORT_EXPNDTR_TOTAMT': 76601000.0,
    'EDC_EXPNDTR_TOTAMT': 417205000.0,
    'PLESR_EXPNDTR_TOTAMT': 98211000.0,
    'LSR_CLTUR_EXPNDTR_TOTAMT': 181536000.0,
    'ETC_EXPNDTR_TOTAMT': 125027000.0,
    'FD_EXPNDTR_TOTAMT': 416217000.0},
   {'STDR_YYQU_CD': '20191',

In [16]:
response.keys()

AttributeError: 'str' object has no attribute 'keys'

In [22]:
response["VwsmAdstrdNcmCnsmpW"]['list_total_count']

11050

In [25]:
len(response["VwsmAdstrdNcmCnsmpW"]['row'])

1000

In [26]:
response["VwsmAdstrdNcmCnsmpW"]['row'][0]

{'STDR_YYQU_CD': '20242',
 'ADSTRD_CD': '11290725',
 'ADSTRD_CD_NM': '월곡2동',
 'MT_AVRG_INCOME_AMT': 3138026.0,
 'INCOME_SCTN_CD': '07',
 'EXPNDTR_TOTAMT': 6095681000.0,
 'FDSTFFS_EXPNDTR_TOTAMT': 1742619000.0,
 'CLTHS_FTWR_EXPNDTR_TOTAMT': 120263000.0,
 'LVSPL_EXPNDTR_TOTAMT': 41454000.0,
 'MCP_EXPNDTR_TOTAMT': 947217000.0,
 'TRNSPORT_EXPNDTR_TOTAMT': 547642000.0,
 'EDC_EXPNDTR_TOTAMT': 131058000.0,
 'PLESR_EXPNDTR_TOTAMT': 157450000.0,
 'LSR_CLTUR_EXPNDTR_TOTAMT': 381918000.0,
 'ETC_EXPNDTR_TOTAMT': 224631000.0,
 'FD_EXPNDTR_TOTAMT': 1801429000.0}

In [28]:
response["VwsmAdstrdNcmCnsmpW"]['row'][0]

{'STDR_YYQU_CD': '20241',
 'ADSTRD_CD': '11545690',
 'ADSTRD_CD_NM': '시흥3동',
 'MT_AVRG_INCOME_AMT': 2516251.0,
 'INCOME_SCTN_CD': '06',
 'EXPNDTR_TOTAMT': 501526000.0,
 'FDSTFFS_EXPNDTR_TOTAMT': 123149000.0,
 'CLTHS_FTWR_EXPNDTR_TOTAMT': 1842000.0,
 'LVSPL_EXPNDTR_TOTAMT': 25596000.0,
 'MCP_EXPNDTR_TOTAMT': 17315000.0,
 'TRNSPORT_EXPNDTR_TOTAMT': 189462000.0,
 'EDC_EXPNDTR_TOTAMT': 7185000.0,
 'PLESR_EXPNDTR_TOTAMT': 19648000.0,
 'LSR_CLTUR_EXPNDTR_TOTAMT': 14380000.0,
 'ETC_EXPNDTR_TOTAMT': 9216000.0,
 'FD_EXPNDTR_TOTAMT': 93733000.0}

In [30]:
kor_cols = ["기준_년분기_코드",
"행정동_코드",
"행정동_코드_명",
"월_평균_소득_금액",
"소득_구간_코드",
"지출_총금액",
"식료품_지출_총금액",
"의류_신발_지출_총금액",
"생활용품_지출_총금액",
"의료비_지출_총금액",
"교통_지출_총금액",
"교육_지출_총금액",
"유흥_지출_총금액",
"여가_문화_지출_총금액",
"기타_지출_총금액",
"음식_지출_총금액"]

In [33]:
result = {}
for item in response["VwsmAdstrdNcmCnsmpW"]['row']:
    for key, value in zip(kor_cols, item.values()):
        if type(value) == float:
            result.setdefault(key, []).append(int(value))
        else:
            result.setdefault(key, []).append(value)
df = pd.DataFrame(result)
df

,기준_년분기_코드,행정동_코드,행정동_코드_명,월_평균_소득_금액,소득_구간_코드,지출_총금액,식료품_지출_총금액,의류_신발_지출_총금액,생활용품_지출_총금액,의료비_지출_총금액,교통_지출_총금액,교육_지출_총금액,유흥_지출_총금액,여가_문화_지출_총금액,기타_지출_총금액,음식_지출_총금액
0,20241,11545690,시흥3동,2516251,06,501526000,123149000,1842000,25596000,17315000,189462000,7185000,19648000,14380000,9216000,93733000
1,20191,11110530,사직동,5208463,09,31889341000,1238314000,158974000,60281000,586427000,188458000,169234000,293797000,1241791000,23670438000,4281627000
2,20191,11110615,종로1·2·3·4가동,3350350,07,77584610000,3618998000,7478066000,861970000,4123252000,3236609000,2062644000,2398515000,13520753000,23729021000,16554782000
3,20191,11110650,혜화동,3472006,07,7826497000,1354887000,215665000,77222000,1129580000,20145000,195279000,415196000,565923000,361926000,3490674000
4,20191,11110680,창신2동,2179485,05,670987000,143195000,23323000,11149000,142754000,945000,0,17411000,32513000,18104000,281593000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20242,11260630,묵2동,2533867,06,4045653000,872624000,154118000,194267000,685803000,294431000,69070000,279448000,288417000,70400000,1137075000
996,20242,11290525,성북동,3470748,07,4064721000,1011697000,194663000,32064000,493731000,20348000,275371000,36695000,227266000,328191000,1444695000
997,20242,11290610,보문동,3162623,07,3063701000,589515000,43187000,40859000,234881000,1279620000,58246000,46370000,132885000,68865000,569273000
998,20242,11290650,정릉4동,3038165,07,3806957000,1173594000,50584000,9416000,564567000,726547000,92411000,66595000,159970000,85004000,878269000
999,20242,11290715,월곡1동,3294213,07,3083861000,761314000,27143000,357285000,405049000,428919000,256772000,48156000,135297000,86896000,577030000

# 전체 데이터 수집

In [1]:
import os
import re
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup as bs
from dotenv import load_dotenv
load_dotenv()

True

In [40]:
start = 1
end = 1000
page = 1
total_page = 1
result = {}
while page <= total_page:
    url = f"http://openapi.seoul.go.kr:8088/{os.getenv("seoul_api")}/json/VwsmAdstrdNcmCnsmpW/{start}/{end}"
    r = requests.get(url)
#     print(r.url)
#     print(r.status_code)
    response = r.json()
    if total_page ==1:
        total_page = response["VwsmAdstrdNcmCnsmpW"]['list_total_count'] // 1000 + 1

    
    kor_cols = ["기준_년분기_코드", "행정동_코드", "행정동_코드_명", "월_평균_소득_금액",
                "소득_구간_코드", "지출_총금액", "식료품_지출_총금액", "의류_신발_지출_총금액",
                "생활용품_지출_총금액", "의료비_지출_총금액", "교통_지출_총금액",
                "교육_지출_총금액", "유흥_지출_총금액", "여가_문화_지출_총금액",
                "기타_지출_총금액", "음식_지출_총금액"]
    
 
    for item in response["VwsmAdstrdNcmCnsmpW"]['row']:
        for key, value in zip(kor_cols, item.values()):
            if type(value) == float:
                result.setdefault(key, []).append(int(value))
            else:
                result.setdefault(key, []).append(value)
    
    print(f"{page}/{total_page}데이터 수집중", end="\r")
#     print(f"{start}, {end}")
    start += 1000
    end += 1000
    page += 1
    
df = pd.DataFrame(result)
df

,기준_년분기_코드,행정동_코드,행정동_코드_명,월_평균_소득_금액,소득_구간_코드,지출_총금액,식료품_지출_총금액,의류_신발_지출_총금액,생활용품_지출_총금액,의료비_지출_총금액,교통_지출_총금액,교육_지출_총금액,유흥_지출_총금액,여가_문화_지출_총금액,기타_지출_총금액,음식_지출_총금액
0,20241,11545690,시흥3동,2516251,06,501526000,123149000,1842000,25596000,17315000,189462000,7185000,19648000,14380000,9216000,93733000
1,20191,11110530,사직동,5208463,09,31889341000,1238314000,158974000,60281000,586427000,188458000,169234000,293797000,1241791000,23670438000,4281627000
2,20191,11110615,종로1·2·3·4가동,3350350,07,77584610000,3618998000,7478066000,861970000,4123252000,3236609000,2062644000,2398515000,13520753000,23729021000,16554782000
3,20191,11110650,혜화동,3472006,07,7826497000,1354887000,215665000,77222000,1129580000,20145000,195279000,415196000,565923000,361926000,3490674000
4,20191,11110680,창신2동,2179485,05,670987000,143195000,23323000,11149000,142754000,945000,0,17411000,32513000,18104000,281593000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11045,20243,11620735,대학동,2622408,06,2565461000,1082769000,14441000,3555000,306314000,1830000,73136000,83938000,125324000,80517000,793637000
11046,20243,11650570,반포2동,6812331,09,591390000,170387000,1136000,0,89215000,3507000,151776000,0,24476000,18836000,132057000
11047,20243,11650590,방배본동,4856162,08,6368143000,337715000,38519000,50812000,343531000,198834000,129994000,21332000,135738000,4685978000,425690000
11048,20243,11680640,역삼1동,3607265,07,462852749000,2875360000,1065433000,347696000,10855447000,217119000,2313910000,1022743000,376215448000,60753193000,7186400000
11049,20243,11680655,도곡1동,5412484,09,12575577000,358391000,16057000,36620000,3905612000,251401000,187397000,19650000,7053322000,91994000,655133000

# xml 로 수집후 정리

In [1]:
import os
import re
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup as bs
from dotenv import load_dotenv
load_dotenv()

True

In [79]:
start = 1
end = 1000
page = 1
total_page = 1
result = {}
while page <= total_page:
    url = f"http://openapi.seoul.go.kr:8088/{os.getenv("seoul_api")}/xml/VwsmAdstrdNcmCnsmpW/{start}/{end}"
    r = requests.get(url)
    response = bs(r.text, 'xml')
    
    if total_page ==1:
        total_page = int(response.select_one('list_total_count').text) // 1000 + 1

    
    kor_cols = ["기준_년분기_코드", "행정동_코드", "행정동_코드_명", "월_평균_소득_금액",
                "소득_구간_코드", "지출_총금액", "식료품_지출_총금액", "의류_신발_지출_총금액",
                "생활용품_지출_총금액", "의료비_지출_총금액", "교통_지출_총금액",
                "교육_지출_총금액", "유흥_지출_총금액", "여가_문화_지출_총금액",
                "기타_지출_총금액", "음식_지출_총금액"]
    row = response.select_one('row')
    tags = [tags.name for tags in row.find_all()]
    for tag, kor_col in zip(tags, kor_cols):
        for value in response.select(tag):
            result.setdefault(kor_col, []).append(value.text)
    
    print(f"{page}/{total_page}데이터 수집중", end="\r")
#     print(f"{start}, {end}")
    start += 1000
    end += 1000
    page += 1
    
df = pd.DataFrame(result)
df

,기준_년분기_코드,행정동_코드,행정동_코드_명,월_평균_소득_금액,소득_구간_코드,지출_총금액,식료품_지출_총금액,의류_신발_지출_총금액,생활용품_지출_총금액,의료비_지출_총금액,교통_지출_총금액,교육_지출_총금액,유흥_지출_총금액,여가_문화_지출_총금액,기타_지출_총금액,음식_지출_총금액
0,20241,11545690,시흥3동,2516251,06,501526000,123149000,1842000,25596000,17315000,189462000,7185000,19648000,14380000,9216000,93733000
1,20191,11110530,사직동,5208463,09,31889341000,1238314000,158974000,60281000,586427000,188458000,169234000,293797000,1241791000,23670438000,4281627000
2,20191,11110615,종로1·2·3·4가동,3350350,07,77584610000,3618998000,7478066000,861970000,4123252000,3236609000,2062644000,2398515000,13520753000,23729021000,16554782000
3,20191,11110650,혜화동,3472006,07,7826497000,1354887000,215665000,77222000,1129580000,20145000,195279000,415196000,565923000,361926000,3490674000
4,20191,11110680,창신2동,2179485,05,670987000,143195000,23323000,11149000,142754000,945000,0,17411000,32513000,18104000,281593000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11045,20243,11620735,대학동,2622408,06,2565461000,1082769000,14441000,3555000,306314000,1830000,73136000,83938000,125324000,80517000,793637000
11046,20243,11650570,반포2동,6812331,09,591390000,170387000,1136000,0,89215000,3507000,151776000,0,24476000,18836000,132057000
11047,20243,11650590,방배본동,4856162,08,6368143000,337715000,38519000,50812000,343531000,198834000,129994000,21332000,135738000,4685978000,425690000
11048,20243,11680640,역삼1동,3607265,07,462852749000,2875360000,1065433000,347696000,10855447000,217119000,2313910000,1022743000,376215448000,60753193000,7186400000
11049,20243,11680655,도곡1동,5412484,09,12575577000,358391000,16057000,36620000,3905612000,251401000,187397000,19650000,7053322000,91994000,655133000